hashicorp/terraform-plugin-framework

- docs/design/resource-registration.md
- docs/design/runtime-state.md
- docs/design/schemas.md
Add recommendations and the justifications we made when deciding things to the design documents we've made decisions about.
> Capture more decisions made about designs

- docs/design/factories.md
- docs/design/structs-interfaces.md
Add recommendations and the justifications we made when deciding things to the design documents we've made decisions about.
> Capture decisions made about designs.

- data_source.go
- provider.go
- request.go
- resource.go
> Provider, Resource, and DataSource types

- .changelog/32.txt
Got missed as part of the PR, just adding it now.
> Add changelog entry for #32.

- .changelog/44.txt
- .changelog/46.txt
Add a couple more missed changelogs.
> Add changelog entries for #44, #46

- plan.go
- state.go
- state_test.go
This is the final piece that closes #16.
We don't need setters on `Config`.
> Implement State.Set, State.SetAttribute, Plan.Set, Plan.SetAttribute

- resource.go
> add context to NewResource params

- data_source.go
> If NewResource gets a context, so should NewDataSource.

- schema/attribute.go
Add a comment to schema.Attribute.Equal.
> Make golint happy.

- go.mod
- go.sum
- internal/proto6/schema_test.go
- internal/reflect/build_value_test.go
- internal/reflect/helpers_test.go
- internal/reflect/interfaces_test.go
- internal/reflect/number_test.go
- internal/reflect/pointer_test.go
- internal/reflect/struct_test.go
Had to rewrite some test fixtures because error formats changed.
> Update to terraform-plugin-go v0.3.1

- docs/design/README.md
Provide some brief context for anyone browsing the repo.
> Create README.md for design docs folder

- attr/type.go
- internal/reflect/interfaces.go
- internal/reflect/map.go
- internal/reflect/number.go
- internal/reflect/number_test.go
- internal/reflect/pointer.go
- internal/reflect/pointer_test.go
- internal/reflect/primitive.go
- internal/reflect/primitive_test.go
- internal/reflect/slice.go
- internal/reflect/struct.go
- internal/testing/types/boolwithvalidate.go
- internal/testing/types/diags.go
- internal/testing/types/numberwithvalidate.go
- internal/testing/types/stringwithvalidate.go
- tfsdk/attribute_test.go
- tfsdk/config.go
- tfsdk/config_test.go
- tfsdk/plan.go
- tfsdk/plan_test.go
- tfsdk/state.go
- tfsdk/state_test.go
Closes #127
No CHANGELOG is necessary as this functionality has not been released yet.
> attr: Add attribute path parameter to (TypeWithValidate).Validate() method

- tfsdk/resource.go
> Fix minor typo

- .changelog/179.txt
- go.mod
- go.sum
- internal/reflect/map_test.go
- internal/reflect/slice.go
- internal/reflect/struct_test.go
- tfsdk/attribute.go
- tfsdk/attribute_test.go
- tfsdk/plan_test.go
- tfsdk/schema.go
- tfsdk/schema_test.go
- tfsdk/serve.go
- tfsdk/serve_provider_test.go
- tfsdk/serve_test.go
- tfsdk/state_test.go
- tfsdk/tftypes_value_test.go
- types/float64.go
- types/int64.go
- types/list.go
- types/list_test.go
- types/map.go
- types/map_test.go
- types/object.go
- types/primitive_test.go
- types/set.go
- types/set_test.go
> go get github.com/hashicorp/terraform-plugin-go@v0.4.0

- docs/design/attribute-path.md
Write up some thoughts on the design space of attribute paths.
Part of resolving #81.
> Add a design doc for attribute paths.

- .github/CONTRIBUTING.md
> Update Contributing Guide with additional unit testing information

- .github/CONTRIBUTING.md
> Update Contributing Guide with Changelog and Dependency Update information

- internal/fromproto6/configureprovider.go
- internal/fromproto6/configureprovider_test.go
- internal/fwserver/server_configureprovider.go
- internal/fwserver/server_configureprovider_test.go
- internal/proto6server/serve.go
- internal/proto6server/serve_test.go
- internal/toproto6/configureprovider.go
- internal/toproto6/configureprovider_test.go
> internal: Migrate ConfigureProvider RPC to fromproto6, fwserver, toproto6

- internal/fromproto6/importresourcestate.go
- internal/fromproto6/importresourcestate_test.go
- internal/fwserver/server_importresourcestate.go
- internal/fwserver/server_importresourcestate_test.go
- internal/proto6server/serve_import.go
- internal/proto6server/serve_import_test.go
- internal/toproto6/importedresource.go
- internal/toproto6/importresourcestate.go
- internal/toproto6/state.go
- internal/toproto6/state_test.go
> internal: Migrate ImportResourceState RPC to fromproto6, fwserver, and toproto6

- internal/fromproto6/providermeta.go
- internal/fromproto6/providermeta_test.go
- internal/fromproto6/readdatasource.go
- internal/fromproto6/readdatasource_test.go
- internal/fwserver/server_readdatasource.go
- internal/fwserver/server_readdatasource_test.go
- internal/proto6server/serve.go
- internal/toproto6/readdatasource.go
- internal/toproto6/readdatasource_test.go
> internal: Migrate ReadDataSource RPC to fromproto6, fwserver, and toproto6

- internal/fromproto6/rawstate_test.go
- internal/fromproto6/upgraderesourcestate.go
- internal/fromproto6/upgraderesourcestate_test.go
- internal/fwserver/server_upgraderesourcestate.go
- internal/fwserver/server_upgraderesourcestate_test.go
- internal/proto6server/serve.go
- internal/toproto6/upgraderesourcestate.go
- internal/toproto6/upgraderesourcestate_test.go
- tfsdk/resource_upgrade_state.go
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/340
> internal: Migrate UpgradeResourceState RPC to fromproto6, fwserver, and toproto6

- internal/fwserver/server_configureprovider_test.go
- internal/proto6server/server_configureprovider_test.go
> internal: Implement fwserver ConfigureProvider testing and update proto6server testing

- .github/workflows/ci-go.yml
- README.md
Closes #372
Verbiage is borrowed from terraform-plugin-sdk's README.
> Update README and CI to reflect 1.17 and 1.18 support

- tfsdk/block.go
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/326
> tfsdk: Clarify NestingMode requirement in Block Go documentation

- .github/CONTRIBUTING.md
- website/README.md
This adds a website README file
> chore: readme & contributing

- website/docs/plugin/framework/resources/import.mdx
- website/docs/plugin/framework/resources/state-upgrade.mdx
* Use the new path abstraction #390
> Update docs to reflect breaking changes in v0.10.0 for path.Path

- README.md
Plugin-framework supports both 5 and 6 versions of the Terraform Plugin Protocol.
> Readme update - TF CLI compatibility

- tfsdk/attribute.go
- tfsdk/block.go
- website/docs/plugin/framework/schemas.mdx
> tfsdk: Clarify Attribute and Block type DeprecationMessage field usage

- tfsdk/request.go
- website/docs/plugin/framework/resources/index.mdx
- website/docs/plugin/framework/resources/plan-modification.mdx
> website: Add Resource Destroy Plan Diagnostics section

- tfsdk/attribute.go
- website/docs/plugin/framework/schemas.mdx
Reference: https://github.com/hashicorp/terraform/pull/31576
> tfsdk: Clarify Attribute type DeprecationMessage documentation for Terraform 1.2.7 and later

- internal/fwserver/server_planresourcechange_test.go
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/183
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/456
> internal/fwserver: Add unit test for no configuration change plan which has modified and unmodified Computed attributes

- website/docs/plugin/framework/migrating/resources/crud.mdx
> docs: Additional migration notes on Update handling and RemoveResource handling

- .github/workflows/ci-go.yml
Reference: https://github.com/hashicorp/terraform/releases/tag/v1.3.0
> .github/workflows: Add Terraform 1.3.x to testing matrix

- website/data/plugin-framework-nav-data.json
- website/docs/plugin/framework/data-sources/index.mdx
- website/docs/plugin/framework/data-sources/timeouts.mdx
- website/docs/plugin/framework/migrating/data-sources/index.mdx
- website/docs/plugin/framework/migrating/data-sources/timeouts.mdx
- website/docs/plugin/framework/migrating/resources/index.mdx
- website/docs/plugin/framework/migrating/resources/timeouts.mdx
- website/docs/plugin/framework/resources/index.mdx
- website/docs/plugin/framework/resources/timeouts.mdx
> Update docs to include timeouts

- provider/schema/schema.go
Forgot to modify after duplicating the datasource type.
> provider/schema: Fix Go documentation for Schema type

- internal/fwserver/server.go
Signed-off-by: Julien Pivotto <roidelapluie@o11y.eu>
> Fix typo: Provier -> Provider

- website/data/plugin-framework-nav-data.json
- website/docs/plugin/framework/index.mdx
- website/docs/plugin/framework/migrating/benefits.mdx
- website/docs/plugin/framework/migrating/index.mdx
Closes #511
Reference: https://github.com/hashicorp/terraform-docs-common/pull/252
This page is a continuation of the higher level benefits noted on the new page in the top-level Plugin Development section.
> website: Introduce benefits page to migration guide

- website/docs/plugin/framework/handling-data/accessing-values.mdx
- website/docs/plugin/framework/handling-data/attributes.mdx
- website/docs/plugin/framework/handling-data/writing-state.mdx
- Found some broken links while reading about conversion rules/data
> docs: fix for conversion-rules links

- website/docs/plugin/framework/resources/delete.mdx
- website/docs/plugin/framework/resources/update.mdx
- Removes extra parens in two links in MDX
> [docs] Fixing extra parens in MDX links

- providerserver/providerserver.go
- website/docs/plugin/framework/acctests.mdx
Closes #662
These were the only Go import specific references I could find. 👍
> all: Updates for terraform-plugin-testing

- docs/design/plan-modification.md
- Reverting a change from #670 that changed a design doc meant to be a snapshot
> Revert change to design doc artifact

- .changes/unreleased/NOTES-20230303-091808.yaml
- .github/workflows/ci-go.yml
- README.md
- go.mod
- website/docs/plugin/framework/migrating/index.mdx
> Updating to Go 1.19

- .github/workflows/ci-go.yml
Reference: https://github.com/hashicorp/terraform-providers-devex-internal/issues/139
> .github/workflows: Test on Terraform 1.4.* versions

- website/data/plugin-framework-nav-data.json
- website/docs/plugin/framework/migrating/index.mdx
- website/docs/plugin/framework/migrating/mux.mdx
- website/docs/plugin/framework/migrating/providers/index.mdx
- website/docs/plugin/framework/migrating/testing.mdx
> website: Move migration guide muxing content to standalone page

- .changes/unreleased/ENHANCEMENTS-20230314-144231.yaml
- .changes/unreleased/ENHANCEMENTS-20230314-144232.yaml
- .changes/unreleased/ENHANCEMENTS-20230314-144233.yaml
- .changes/unreleased/ENHANCEMENTS-20230314-144234.yaml
- types/basetypes/bool.go
- types/basetypes/bool_test.go
- types/basetypes/float64.go
- types/basetypes/float64_test.go
- types/basetypes/int64.go
- types/basetypes/int64_test.go
- types/basetypes/string.go
- types/basetypes/string_test.go
- types/bool_value.go
- types/float64_value.go
- types/int64_value.go
- types/string_value.go
> types: Go pointer value constructors and getters for Bool, Float64, Int64, and String

- website/docs/plugin/framework/diagnostics.mdx
> website: Enhance diagnostics page with references to diag.New functions and more examples

- website/docs/plugin/framework/handling-data/custom-types.mdx
Fix minor errors / typos in custom-types.mdx
> Fix example errors in custom-types.mdx

- .changes/unreleased/BUG FIXES-20230623-172651.yaml
- internal/fwserver/server.go
- internal/proto5server/server_getproviderschema_test.go
- internal/proto6server/server_getproviderschema_test.go
> internal/fwserver: Delay resource schema caching to occur after GetProviderSchema RPC

- .changes/unreleased/BUG FIXES-20230720-143705.yaml
Reference: https://github.com/hashicorp/terraform-plugin-framework/pull/792
> Update CHANGELOG for #792

- .changes/unreleased/NOTES-20230906-055849.yaml
- .github/workflows/ci-go.yml
- README.md
- go.mod
- tools/go.mod
- website/docs/plugin/framework/migrating/index.mdx
> all: Update Go Module to Go 1.20

- website/docs/plugin/framework/provider-servers.mdx
Reference: https://discuss.hashicorp.com/t/plugin-protocol-version-6-compatibility-with-terraform-cli-v1-0-8/59621
> docs: Add protocol version 6 compatibility note with mux

- website/docs/plugin/framework/resources/create.mdx
Small doc fix that was mentioned in one of our slack channels
> Fixed documentation resource model code

- website/docs/plugin/framework/index.mdx
So its not just a sidebar link to find the new concept and its documentation.
> website: Add Functions to homepage Key Concepts section

- website/docs/plugin/framework/functions/index.mdx
Per our offline conversation, attempting to give users who want to build a function but are new to provider development a path forward, just in case they land on this page from SEO or due to direct links.
> Adding section for extremely new users to provider development

- website/docs/plugin/framework/functions/parameters/object.mdx
> website/docs: Fix object parameter attr.Type example

- internal/fwserver/server_deleteresource.go
- resource/resource.go
- resource/schema/defaults/string.go
- resource/schema/planmodifier/bool.go
- resource/schema/planmodifier/float64.go
- resource/schema/planmodifier/int64.go
- resource/schema/planmodifier/list.go
- resource/schema/planmodifier/map.go
- resource/schema/planmodifier/number.go
- resource/schema/planmodifier/object.go
- resource/schema/planmodifier/set.go
- resource/schema/planmodifier/string.go
- schema/validator/bool.go
- schema/validator/float64.go
- schema/validator/int64.go
- schema/validator/list.go
- schema/validator/map.go
- schema/validator/number.go
- schema/validator/object.go
- schema/validator/set.go
- schema/validator/string.go
Found while working through #931 🎸
> all: Miscellaneous doc fixes

- website/docs/plugin/framework/handling-data/types/int64.mdx
> website/docs: Link fix on int64 type page

- website/docs/plugin/framework/functions/testing.mdx
> website: Update testing documentation to utilize new `statecheck` and `knownvalue` packages

- website/docs/plugin/framework/resources/read.mdx
- website/docs/plugin/framework/resources/update.mdx
> website: Fix plan modifier examples

- .changes/unreleased/BUG FIXES-20240917-163716.yaml
- internal/proto5server/server_getmetadata_test.go
- internal/proto5server/server_getproviderschema_test.go
- internal/proto6server/server_getmetadata_test.go
- internal/proto6server/server_getproviderschema_test.go
- internal/toproto5/server_capabilities.go
- internal/toproto5/server_capabilities_test.go
- internal/toproto6/server_capabilities.go
- internal/toproto6/server_capabilities_test.go
> add missing capability MoveResourceState

- website/docs/plugin/framework/functions/parameters/int64.mdx
Our branch protection rules forbid me from making small doc fixes before merging PRs, so here's a one-liner 🙂
> website/docs: Quick fix on header in parameter docs

- .github/CODEOWNERS
Adding permission to adjust:
* docs
* images
* website's README
> Ensure edu team can adjust documentation related files
