hashicorp/terraform-plugin-framework

docs/design/panic-error.md
Add a design doc that proposes a set of conventions and trade offs
involved in deciding whether to use a panic or an error in the
framework. The goal of this document is to help us achieve consistency
on this, and get the most out of Go's tools around exceptional behavior.
This proposal can be summarised as "use whichever is most appropriate
for the situation you're in", but outlines a number of different
guidelines to use and things to consider when determining which is most
appropriate.
=> Add design doc for panics and errors.

docs/design/resource-registration.md
How do we tell a provider about which resources and data sources exist,
so it can list their schemas and route requests to them?
=> Add design doc on resource registration.

docs/design/factories.md
We want to instantiate new instances of resources, data sources, and
providers so that we can have some isolation at runtime, but either the
provider defined the type of the resource/data source/provider and we
don't know how to create new instance of it, or the framework defined
the type and the provider needs to supply values for it, which the
framework needs to get from the provider when creating a new instance of
it.
This document explores different ways to achieve that.
=> Add design doc about the factory problem.

request.go, response.go
closes #13 
This PR defines:
* `ConfigureProviderRequest`
*  `ConfigureProviderResponse`
*  `{Create,Read,Update,Delete}ResourceRequest` 
*  `{Create,Read,Update,Delete}ResourceResponse`
Needs `State` and `Plan` types (#26) before it will compile.
=> Request and response types

.changelog/29.txt, go.mod, go.sum, types/bool.go, types/bool_test.go, types/number.go, types/number_test.go, types/primitive.go, types/primitive_test.go, types/string.go, types/string_test.go
This adds to #28 by creating implementations of the attr.Type interface for our primitive types: bools, numbers, and strings.
This is likewise a split of code originally written for #11 that is being split out into its own PR for easier review. (Or, at least, review will be easier when #28 is merged, which should happen before this is merged.)
=> Add primitive types.

internal/reflect/helpers.go, internal/reflect/helpers_test.go, internal/reflect/interfaces.go, internal/reflect/interfaces_test.go, internal/reflect/map.go, internal/reflect/map_test.go, internal/reflect/number.go, internal/reflect/number_test.go, internal/reflect/options.go, internal/reflect/pointer.go, internal/reflect/pointer_test.go, internal/reflect/primitive.go, internal/reflect/primitive_test.go, internal/reflect/reflection.go, internal/reflect/reflection_test.go, internal/reflect/slice.go, internal/reflect/struct.go, internal/reflect/struct_test.go
Add a package that will let us build reflect.Values from any Go type and
populate them with the data from any tftypes.Value. This culminates in
the reflect.Into function, which lets us have json.Unmarshal-esque
behavior but for tftypes.Values.
This will be used later for making aggregate types easier to work with.
=> Add internal/reflect package

internal/reflect/reflection.go
We need to be setting the Elem, not the pointer value.
This is covered by and discovered by the complex types being added.
=> Fix a bug in reflect.Into.

.changelog/36.txt, types/list.go, types/list_test.go
Added a list type, with tests. The tests are not exhaustive, but cover
all the code paths for now.
=> Add support for list types.

attr/type.go
Adds the `ObjectType` interface, needed for reflection work.
The `AttributeTypes()` function could also be called `GetAttributeTypes()` - I've tried to make it consistent with `Type.TerraformType()`.
Will add changelog entry when approved.
=> add attr.ObjectType

.changelog/38.txt, internal/reflect/number.go, internal/reflect/struct_test.go, types/list.go, types/object.go, types/object_test.go
Adds the Object type and the ObjectType type. typetypetype.
Depends on #41.
=> Add support for objects

attr/type.go, config.go, plan.go, request.go, response.go, schema/attribute.go, schema/nested_attributes.go, schema/schema.go, schema/schema_test.go, state.go, state_test.go, types/list.go, types/object.go, types/primitive.go, types/primitive_test.go
The changes to `internal/reflect` on `main` made rather a mess of `katystate3`. We're up to `katystate5` now.
The main work here is the addition of `ApplyTerraform5AttributePathStep` to all schema types, implementing the `tftypes.AttributePathStepper` interface so that we can traverse the schema with [`tftypes.WalkAttributePath`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-go@v0.3.0/tftypes#WalkAttributePath).
=> Implement State, State.Get, State.GetAttribute, Config, Plan

docs/design/plan-modification.md
The first step towards #34.
I'm not fully happy with the `RequiresReplaceIf` part of the proposal and am looking for feedback. The main puzzle is how to keep verbosity low in the provider code while keeping the interface flexible enough.
=> Plan modification design doc

docs/design/attr-value-access.md
Add a design doc describing the problem of accessing a single
attribute's value, and proposing a solution for it.
=> Add attr.Value access design doc.

.changelog/72.txt, tfsdk/serve.go
We need access to the tfprotov6.ProviderServer underlying `tfsdk.Serve`
for things like testing and muxing. Add a function that will expose it.
=> Add support for retrieving tfprotov6.ProviderServer.

tfsdk/provider.go
The Provider interface's GetSchema method told provider developers to
return nil, but they can't actually return nil anymore. Update to
correct the guidance.
=> Fix out of date guidance for GetSchema.

.changelog/74.txt, tfsdk/serve.go, tfsdk/serve_test.go
Don't pass empty state values into response types. Instead, default to
the prior or current state, which is almost always what providers will
want.
(Partially?) resolves #51.
=> Default to prior state in responses.

.changelog/79.txt, internal/proto6/schema_test.go, schema/nested_attributes.go, tfsdk/serve_provider_test.go, tfsdk/serve_test.go
Fill in tests for maps.
Add MapNestedAttributes and tests for it.
=> Add support for MapNestedAttributes.

.changelog/90.txt, tfsdk/data_source.go, tfsdk/request.go, tfsdk/resource.go, tfsdk/response.go, tfsdk/serve.go, tfsdk/serve_provider_test.go, tfsdk/serve_resource_two_test.go, tfsdk/serve_test.go
Epic: #34 
Design doc: #64 
Plan modification functionality has two parts:
1. The `ResourceWithModifyPlan` interface (this PR)
2. `schema.Attribute.PlanModifiers` (future PR)
This PR adds the `ResourceWithModifyPlan` interface, allowing resources to define an optional `ModifyPlan` function.
```go
type ResourceWithModifyPlan interface {
Resource
ModifyPlan(context.Context, ModifyResourcePlanRequest, *ModifyResourcePlanResponse)
}
```
=> Implement ResourceWithModifyPlan interface

README.md
We actually need Terraform v1.0.3 or higher, not 0.15.
=> Fix version constraints in README.

tfsdk/attribute_test.go
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/17
This was covered already by the `(Config).GetAttribute()` call in the function, however this testing required merging the new `internal/testing/types` package.
=> tfsdk: Add unit testing covering attr.TypeWithValidate in (Attribute).validate()

tfsdk/config.go, tfsdk/plan.go, tfsdk/serve_test.go, tfsdk/state.go
Fixes #106 
Instead of returning an error when GetAttribute is called on a nil state, plan, or config, return nil, provided the attribute path is valid and appears in the schema.
In a nil state/plan/config, the value of any given schema attribute should be nil.
=> return nil when GetAttribute called on nil state

tfsdk/serve_test.go
Close #121
Least invasive change to fix testing race conditions.
=> tfsdk: Exit early in TestServerPlanResourceChange on error diagnostics

.changelog/118.txt, tfsdk/attribute.go
Closes #112.
Don't attempt validation if the attribute is missing from configuration.
=> Fix `SingleNestedAttribute` validation failure

tfsdk/serve_import.go, tfsdk/serve_import_test.go
Closes #163
Prior to the code fix:
```
--- FAIL: TestServerImportResourceState/imported_resource_conversion_error (0.00s)
/Users/bflad/src/github.com/hashicorp/terraform-plugin-framework/tfsdk/serve_import_test.go:202: Unexpected diff in response (+wanted, -got):   &tfprotov6.ImportResourceStateResponse{
- 	ImportedResources: []*tfprotov6.ImportedResource{nil},
+ 	ImportedResources: []*tfprotov6.ImportedResource{&{TypeName: "test_import_state"}},
  	Diagnostics:       {&{Severity: s"ERROR", Summary: "Error converting imported resource response", Detail: "An unexpected error was encountered when converting the imported"...}},
  }
```
=> tfsdk: Omit ImportedResource from response if error during protocol conversion

tfsdk/schema.go, tfsdk/schema_test.go, tfsdk/serve.go, tfsdk/serve_provider_test.go, tfsdk/serve_resource_three_test.go, tfsdk/serve_resource_two_test.go, tfsdk/serve_test.go
This fixes #175. Essentially, our behavior did exactly what we thought
it did, but didn't combine with Terraform in the ways we thought it
would. We need to set all computed attributes that are null in the
_config_ to unknown, not all computed attributes that are null in the
_plan_ to unknown, because once a computed attribute has a value in
state, it will not have a null plan again unless the provider modifies
the plan to null explicitly. This means once a computed attribute gets a
value, under the existing code, it can't be updated by the provider.
As part of this change, I moved when the null->unknown transform
happens. It used to happen at the very end, which gave provider
developers no opportunity to override the auto-unknown values with
values the provider may know at plan time, …
=> Fix planning.

tfsdk/serve.go, tfsdk/serve_resource_attribute_plan_modifiers_test.go, tfsdk/serve_test.go
Closes #181
Reference: https://github.com/hashicorp/terraform/blob/main/docs/resource-instance-change-lifecycle.md 
`ProposedNewState` is the merged `PriorState` and `Configuration`. This allows us to verify if any configuration changes have occurred.
Previously, any `Computed` attributes would always trigger plan differences due to the unknown marking.
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
~ resource "hashicups_order" "edu" {
~ id           = "1" -> (known after apply)
~ items        = [
~ {
~ coffee   = {
+ description = (known after apply)
id          = 3
~ image       = "/nomad.png" -> (known after apply)
~ name …
```
=> tfsdk: Check ProposedNewState for State differences before marking unknowns for Computed-only attributes in plans

.changelog/185.txt, tfsdk/attribute_test.go, tfsdk/config.go, tfsdk/config_test.go, tfsdk/plan.go, tfsdk/plan_test.go, tfsdk/state.go, tfsdk/state_test.go
Closes #150
Includes more exhaustive unit testing `Config`, `Plan`, and `State` `GetAttribute()` method, which is copied between all of them. Also left TODOs for #186 to follow this up with unknown parent checking.
=> tfsdk: Return null value when missing from Config, Plan, and State GetAttribute() method

.circleci/config.yml
As described in https://github.com/hashicorp/terraform-plugin-framework/issues/19#issuecomment-924838048, this new PR CI job:
- pulls the main branch of terraform-provider-corner
- adds a `replace` directive to the provider's `go.mod` that points to the code on the current branch
- runs the subset of terraform-provider-corner tests that concern resources implemented in the framework
Currently, terraform-provider-corner has one acceptance test for a very basic resource. Once this is set up, we can add further test cases as we encounter them.
=> CI: add terraform-provider-corner integration test job

.changelog/213.txt, tfsdk/attribute_plan_modification.go, tfsdk/attribute_plan_modification_test.go, tfsdk/attribute_test.go, tfsdk/serve_test.go
Fixes #187, supercedes #203.
This changes the logic on our RequiresReplace function in the following
ways:
* if the attribute being modified has not changed, RequiresReplace isn't
changed. This prevents the resource from being destroyed and recreated
when _any_ attribute changes, limiting it only to the attribute with
RequiresReplace set on it.
* if the attribute being modified is computed and is null in the config,
RequiresReplace isn't changed. This prevents the resource from being
destroyed and recreated when the provider returns an unknown value in
the plan, or even a new, provider-controlled value, because it's
unlikely the practitioners expect their resource to be destroyed and
recreated when an attribute out of their control changes. This has the
unfortunate side-effect that …
=> Complicate our RequiresReplace(If) logic.

README.md
We're in a way less experimental state now, and are more accurately
classified as a technical preview.
=> Update verbiage to technical preview.

tfsdk/attribute.go, tfsdk/attribute_plan_modification.go, tfsdk/attribute_plan_modification_test.go, tfsdk/attribute_test.go, tfsdk/block.go, tfsdk/block_test.go, tfsdk/schema.go, tfsdk/serve.go, tfsdk/serve_resource_attribute_plan_modifiers_test.go, tfsdk/serve_test.go
Closes #222
Adds `PlanModifiers` within `Block`s and ensures any children attribute and block plan modifiers of a `Block` are executed.
No changelog entry is necessary unless there is a framework release prior to this support.
=> tfsdk: Support block plan modification

.changelog/232.txt, internal/reflect/generic_attr_value.go, tfsdk/value_as.go, tfsdk/value_as_test.go
Allow for generic handling of attr.Values by special-casing ValueAs
(and, consequently, GetAttribute) to bypass reflection when we want to
just obtain the raw attr.Value.
Fixes #230.
=> Allow using ValueAs into attr.Value.

.changelog/243.txt, tfsdk/serve.go
Closes #239
Reference: https://www.terraform.io/plugin/sdkv2/debugging
Similar to Terraform Plugin SDK, providers need to be executable via debugger and testing processes for instrumenting the provider code. In this workflow, the caller manages the provider lifecycle, rather than Terraform CLI. The Terraform CLI reattach configuration is output to stdout.
Verified in a framework-based provider by:
- `go mod edit -replace=github.com/hashicorp/terraform-plugin-framework=/Users/bflad/src/github.com/hashicorp/terraform-plugin-framework` (use this worktree)
- Updated provider `main` function code to 
```go
func main() {
var debug bool
flag.BoolVar(&debug, "debug", false, "set to true to run the provider with support for debuggers like delve")
flag.Parse()
var err error
ctx := …
```
=> tfsdk: Added Debug field to ServeOpts for running providers via debugger and testing processes

.changelog/252.txt, tfsdk/schema.go, tfsdk/schema_test.go
Closes #250
This restriction does not seem necessary. Updated unit test and also real world verified against Terraform CLI with a test provider.
=> tfsdk: Remove empty schema restriction

.github/workflows/release.yml
Copied from terraform-plugin-sdk. `.goreleaser.yml` is already in place and up to date.
=> .github/workflows: Add release workflow

docs/design/upgrade-resource-state.md
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/42
=> docs/design: Upgrade Resource State

.changelog/pending.txt, tfsdk/serve.go, tfsdk/serve_test.go
Closes #22 (its technically solved already, this is just cherry on top)
Provider developers have a few reasons to directly need a `tfprotov6.ProviderServer` implementation:
- When implementing acceptance testing with terraform-plugin-sdk helper/resource.
- When using terraform-plugin-mux tf6muxserver.NewMuxServer().
- When using terraform-plugin-mux tf6to5server.DowngradeServer().
The current `NewProtocol6Server(Provider)` function enables these use cases, however the implementation is less than ergonomic for provider developers as a wrapping function is required in all cases:
```go
// helper/resource acceptance testing
resource.TestCase{
ProtoV6ProviderFactories: map[string]func() (tfprotov6.ProviderServer, error){
"example": func() (tfprotov6.ProviderServer, error) {
return …
```
=> tfsdk: Introduce new ProviderServer functions, deprecate existing

internal/fromproto6/doc.go, internal/fromproto6/getproviderschema.go, internal/fromproto6/getproviderschema_test.go, internal/fwserver/doc.go, internal/fwserver/server.go, internal/fwserver/server_getproviderschema.go, internal/fwserver/server_getproviderschema_test.go, internal/proto6server/serve.go, internal/proto6server/serve_test.go, internal/toproto6/getproviderschema.go, internal/toproto6/getproviderschema_test.go, internal/toproto6/schema.go, internal/toproto6/schema_test.go, providerserver/providerserver.go
This step of the provider server refactoring introduces a new `internal/fwserver` package that will contain the provider server implementation for any protocol version, there only being a version 6 implementation at the moment. This package will contain only framework-native types that aren't already defined by the `tfsdk` package that are used by provider developers today, which is necessary to prevent import cycles. The protocol specific implementations will then wrap this framework server implementation and handle any necessary conversion of protocol specific types to framework specific types and back. Eventually, the existing `internal/proto6server` implementation will make no reference to any framework …
=> Introduce internal/fwserver package and migrate GetProviderSchema

internal/fromproto6/validatedatasourceconfig.go, internal/fromproto6/validatedatasourceconfig_test.go, internal/fwserver/server.go, internal/fwserver/server_getproviderschema.go, internal/fwserver/server_validatedatasourceconfig.go, internal/fwserver/server_validatedatasourceconfig_test.go, internal/proto6server/serve.go, internal/proto6server/serve_test.go, internal/toproto6/validatedatasourceconfig.go, internal/toproto6/validatedatasourceconfig_test.go
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/299
This introduces framework server caching for data source types and schemas, similar to the provider schema cache, which is needed with other data source RPCs. The same methodology will be applied for resource types and schemas, when the `ValidateResourceConfig` RPC is migrated.
=> internal: Migrate ValidateDataSourceConfig RPC to fromproto6, fwserver, and toproto6

internal/fwserver/schema_validation.go, internal/proto6server/schema_plan_modification.go, internal/toproto6/schema.go, tfsdk/schema.go
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/329
While attributes will be recommended over blocks going forward, we do not want to alarm or cause confusion with provider developers migrating existing schemas from terraform-plugin-sdk. Terraform also does not provide native functionality to help practitioners switch syntax in configurations, so this deprecation notice is considered premature.
=> tfsdk: Remove Go documentation deprecation for Schema type Blocks field

internal/fwserver/server_validatedatasourceconfig.go, internal/proto6server/serve.go
Some minor items caught after the migration:
- Remove `PreparedConfig` from fwserver `ValidateDataSourceConfigResponse` (this field only applied to `ValidateProviderConfigResponse`)
- Fix logging copy-paste
- Remove now unused proto6server `validateDataResourceConfigResponse`
=> internal: ValidateDataSourceConfig RPC tidying

internal/fromproto6/validateresourceconfig.go, internal/fromproto6/validateresourceconfig_test.go, internal/fwserver/server.go, internal/fwserver/server_getproviderschema.go, internal/fwserver/server_getproviderschema_test.go, internal/fwserver/server_validateresourceconfig.go, internal/fwserver/server_validateresourceconfig_test.go, internal/proto6server/serve.go, internal/proto6server/serve_test.go, internal/toproto6/validateresourceconfig.go, internal/toproto6/validateresourceconfig_test.go
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/299
This migration is almost identical to what was done for `ValidateDataSourceConfig`. This introduces framework server caching for resource types and schemas, similar to the data source schema, data source type, and provider schema caches, which is needed with other resource RPCs.
=> internal: Migrate ValidateResourceConfig RPC to fromproto6, fwserver, and toproto6

internal/proto6server/serve.go, internal/proto6server/serve_import.go, internal/proto6server/serve_import_test.go, internal/proto6server/serve_test.go, providerserver/providerserver.go
Closes #299
This completes the migration to the cached data source and resource schema/type handling in the new `internal/fwserver` package. This also removes the previous `Provider` field so that implementation detail is now wholly within the `internal/fwserver` to remove any confusion.
=> internal/proto6server: Always use data source and resource caches, remove intermediate Provider field

internal/fwserver/server.go, internal/fwserver/server_getproviderschema.go, internal/proto6server/serve.go, internal/proto6server/serve_test.go
This introduces provider meta schema handling, similar to provider schema handling. This will ensure a smoother migration for RPCs that require this information, encapsulate the interface type handling within `internal/fwserver`, and prevent extra executions against the `Provider` `GetMetaSchema()` method.
=> internal: Add ProviderMeta handling to fwserver

tfsdk/attribute_plan_modification.go
=> Remove unnecessary conversion to `tftypes` in `AttributePlanModifier`s implementations

.changelog/350.txt, tfsdk/value_as.go, tfsdk/value_from.go, tfsdk/value_from_test.go
fixes https://github.com/hashicorp/terraform-plugin-framework/issues/323
=> New function `ValueFrom` that takes a Go value and populates a compatible `attr.Value`, given a descriptive `attr.Type`

.changelog/354.txt, types/list.go, types/list_test.go, types/map.go, types/map_test.go, types/object.go, types/object_test.go, types/set.go, types/set_test.go
`ToTerraformValue` in all the non _primitive_ types of `attr.Value`, relies on it containing `ElemType` or `AttrsType` to do the conversion to TF types.
But if by mistake one omits setting that, the framework was throwing a panic as it wasn't checking for those fields being not null. Now it does.
=> Prevent `ToTerraformValue` panic when the underlying `attr.Value` types doesn't have type information for its fields

tfsdk/provider.go
Closes #327
Reference: https://www.terraform.io/plugin/framework/providers
To prevent provider developer confusion when referencing the Go documentation, explicitly call out the provider underscore naming convention for data sources and resources. The website documentation already mentions this detail.
Any changes to the error messaging in this case must be made upstream in Terraform CLI.
=> tfsdk: Augment Provider interface GetDataSources and GetResources method Go documentation

.changelog/376.txt, attr/value.go, internal/reflect/pointer_test.go, internal/reflect/primitive_test.go, internal/testing/types/bool.go, internal/testing/types/string.go, tfsdk/config_test.go, tfsdk/convert_test.go, tfsdk/plan_test.go, tfsdk/state_test.go, types/bool.go, types/bool_test.go, types/float64.go, types/float64_test.go, types/int64.go, types/int64_test.go, types/list.go, types/list_test.go, types/map.go, types/map_test.go, types/number.go, types/number_test.go, types/object.go, types/object_test.go, types/set.go, types/set_test.go, types/string.go, types/string_test.go
At the moment, it can be tricky to log or report errors where the aim is to represent a `attr.Value` concrete type. For a `types.Number` for example, it can look like this:
```
{%!s(bool=false) %!s(bool=false) %!s(*big.Float=6.5)}
```
This is not very practitioner friendly, when the aim is to put such representation in a warning or error diagnostic.
This PR provides a new `.String()` method on the `attr.Value` interface, that aims to address this issue. The representation for each type would follow these formatting "rules":
| Type      | Formatting                                | Unknown     | Null     | Example                                       |
| ---------:|:-----------------------------------------:|:-----------:|:--------:|:----------------------------------------------|
| …
=> Add `.String()` method to `attr.Value` interface

website/data/plugin-framework-nav-data.json, website/docs/plugin/framework/acctests.mdx, website/docs/plugin/framework/debugging.mdx, website/docs/plugin/framework/index.mdx, website/docs/plugin/framework/provider-servers.mdx, website/docs/plugin/framework/providers.mdx
Closes #373
Previously, the sdk/v2 and framework documentation have glossed over the difference between a "provider" and the server that actually handles a lot of the implementation details to interface correctly with Terraform CLI and the acceptance testing framework. This page introduces the concept up front so provider developers are aware of this Terraform-specific implementation detail, introduces the Terraform Plugin Protocol with its versioning implications, and provides some reference code.
Other pages are updated to include protocol version 5 information.
Separately, the existing providers page could use some additional details to better describe the methods and their implementation, but that exercise is left for future changes.
=> website: Add Provider Servers page and adjust content for protocol version 5 support

.github/workflows/ci-go.yml
Reference: https://github.com/hashicorp/terraform-provider-corner/pull/70
The upstream `internal/frameworkprovider` package was migrated to `internal/framework6provider` for disambiguation. This will now also perform integration testing across the matrix of Terraform CLI versions that support each protocol in the hopes of catching any particular version-dependent bugs, especially on pre-1.0 Terraform CLI versions.
Cross-platform testing could also be performed if desired, however platform-dependent bugs in this module (and the previous terraform-plugin-sdk module) have been rare or non-existent so it is omitted for now to reduce the potential for false positives.
=> .github/workflows: Add terraform-provider-corner testing for tfprotov5

tfsdk/resource_import.go, tfsdk/resource_upgrade_state.go
This was brought up from internal feedback and is done for consistency with other "optional" interface types across the framework. These interfaces are meant to be extensions to the parent interface type, so they should already support the parent interface methods.
=> tfsdk: Add missing Resource interface declaration in ResourceWithImportState and ResourceWithUpgradeState

.changelog/392.txt, diag/diagnostics.go, diag/diagnostics_test.go
Closes: #391 
Adds the following convenience functions to Diagnostics:
- `ErrorsCount()`
- `WarningsCount()`
- `Errors()`
- `Warnings()`
=> Add convenience functions for `ErrorsCount`, `WarningsCount`, `Errors` and`Warnings`

diag/doc.go, internal/logging/doc.go, internal/reflect/doc.go, internal/testing/doc.go, internal/testing/planmodifiers/doc.go, internal/testing/testprovider/doc.go, path/doc.go, providerserver/doc.go, tfsdk/doc.go, types/doc.go
Reference: https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework
This ensures all current Go packages have Go comment-based documentation for display in editors and on the pkg.go.dev website.
=> all: Add missing package-level Go documentation

path/expressions.go, path/expressions_test.go, path/paths.go, path/paths_test.go
Reference: https://github.com/hashicorp/terraform-plugin-framework-validators/pull/32
No additional CHANGELOG necessary as this package is still unreleased.
=> path: Add Append methods for Paths and Expressions

path/expression.go, path/expression_steps.go, path/expression_steps_test.go, path/expression_test.go, tfsdk/config.go, tfsdk/config_test.go, tfsdk/path_matches.go, tfsdk/path_matches_test.go, tfsdk/plan.go, tfsdk/plan_test.go, tfsdk/state.go, tfsdk/state_test.go
This will also now return an error diagnostic if a given path expression is invalid for the schema data.
The `(path.Expression).MergeExpressions(...path.Expression) Expressions` is a helper method for the common use case of combining an attribute path expression with an incoming collection of expressions to perform generic validation across attributes.
This requires no CHANGELOG entries as it is unreleased functionality.
=> tfsdk: Ensure Config, Plan, and State PathMatches will return null and unknown parent paths

path/expression.go, path/expressions.go, path/path.go, path/paths.go, website/data/plugin-framework-nav-data.json, website/docs/plugin/framework/path-expressions.mdx, website/docs/plugin/framework/paths.mdx, website/docs/plugin/framework/validation.mdx
Closes #81
The website documentation is less than ideal as it introduces these new path and path expression pages as top-level in the already lengthy navigation, however refactoring the website documentation to bundle together and fix wording/flow for all the concepts/pages around schemas, schema-based data such as Config/Plan/State, and paths in a new dedicated section felt out of scope to this feature specific documentation addition.
=> path+website: Additional Go documentation and initial website documentation for paths and path expressions

.changelog/420.txt, path/expression.go, path/path.go
Closes #419
Since the `(Expression).Equal()` method was not checking this additional flag, it was missing the fact it wasn't handled with `Copy()`. The `(Path).Expression()` method should always set that flag to true, since paths are always root path expressions.
=> path: Ensure Expression root flag is appropriately set and checked

.changelog/426.txt, go.mod, go.sum, internal/fwserver/server_upgraderesourcestate.go, internal/fwserver/server_upgraderesourcestate_test.go
Closes: #415 
During unmarshalling of JSON, if there are fields which do not have a corresponding attribute in the schema an error is returned.
A [PR](https://github.com/hashicorp/terraform-plugin-go/pull/213) on terraform-plugin-go addresses this issue.
The `UnmarshalWithOpts` function used in this PR will not be available to `terraform-plugin-framework` until the PR on `terraform-plugin-go` has been merged, tagged and released. Consequently, the build will fail on this PR until that time.
=> Using UnmarshalWithOpts in order to ignore undefined attributes

datasource/data_source.go, datasource/doc.go, provider/doc.go, provider/provider.go, providerserver/doc.go, resource/doc.go, resource/resource.go
Reference: https://github.com/hashicorp/terraform-plugin-framework/pull/432
=> all: Go package documentation updates post datasource, provider, and resource package migration

datasource/data_source.go, internal/fromproto5/providermeta.go, internal/fromproto6/providermeta.go, path/expression.go, path/path.go, provider/provider.go, providerserver/serve_opts.go, resource/resource.go
For whatever reason, the latest release of `golangci-lint` that runs in CI seems to be applying Go 1.19 fmt checks, even though we are pinned on 1.17 still. This is a quick code update to prevent CI failures from existing issues.
=> all: Run Go 1.19 fmt

website/docs/plugin/framework/index.mdx
Docs changes to support migration to devdot. Updated with the following goals:
- Remove "Learn" and "Collection" as a term from docs
- Remove references to docs nav itself
- Remove user-facing URLs that contain the learn or docs domain ([learn.hashicorp.com](https://learn.hashicorp.com/) or [terraform.io](https://terraform.io/)/docs)
=> Update Docs for DevDot Migration

internal/fwschemadata/data_value.go, internal/fwschemadata/data_value_test.go, internal/fwserver/attr_value.go, internal/fwserver/block_plan_modification_test.go
Reference: #468 (unreleased bugs)
Previously, it was possible to get a `Attribute Plan Modification Walk Error` diagnostic when a resource was being created and the `req.AttributeState` was set to `nil` instead of a null value for the given `attr.Value`. This changes the logic to always return a proper `attr.Value`.
Previously, it was possible that while iterating through the plan elements for a list or set collection, that configuration or state elements at the same index may not exist. The logic was off-by-one due to Go's 0-based slice indexing to return early with a null value in those cases.
=> internal/fwserver: Prevent two sources of errors/panics

website/docs/plugin/framework/resources/index.mdx
When reading the documentation on the website while preparing to migrate an existing small-ish provider, I noticed this typo which seems like it was introduced two days ago (https://github.com/hashicorp/terraform-plugin-framework/commit/7541ab15654b00837015180ecdb7f439e604c6cf).
I was expecting to find a Delete function in that example and ended up scrolling up and down for a couple of minutes until I realised there was a typo in the function name.
I did notice the contribution guidelines indicate that typo PR aren't generally accepted, but hopefully this one is more than an innocent typo since it can really confuse people reading the documentation expecting to find a Delete function in that first overview example. If not, I am sorry for the noise.
=> [docs] Typo in resources index: s/Read/Delete/

.changelog/481.txt, internal/fwserver/attribute_validation_test.go, internal/fwserver/schema_plan_modification_test.go, internal/reflect/map.go, types/list.go, types/list_test.go, types/map.go, types/map_test.go, types/set.go, types/set_test.go
This also fixes a bug in `internal/reflect/map.go` where it used the map's own type to Validate elements, which does not seem correct at all.
Fixes https://github.com/hashicorp/terraform-plugin-framework/issues/467
=> Add Validate() to all collections

.golangci.yml
Previously:
```
$ golangci-lint run ./...
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
```
=> Replace deprecated linters with unused

internal/fwschemadata/data_get.go, internal/fwschemadata/data_get_at_path.go, internal/fwschemadata/data_get_at_path_test.go, internal/fwschemadata/data_get_test.go, internal/reflect/build_value_test.go, internal/reflect/into.go, tfsdk/value_as.go, types/list.go, types/map.go, types/object.go, types/set.go
=> Improve diagnostics when types that cannot handle unknown or null are used

website/data/plugin-framework-nav-data.json, website/docs/plugin/framework/data-sources/index.mdx, website/docs/plugin/framework/data-sources/validate-configuration.mdx, website/docs/plugin/framework/providers/index.mdx, website/docs/plugin/framework/providers/validate-configuration.mdx, website/docs/plugin/framework/resources/index.mdx, website/docs/plugin/framework/resources/validate-configuration.mdx, website/docs/plugin/framework/validation.mdx
In an effort to show provider developers the per-concept functionality, dedicated pages have been created.
This also moves the current providers page as an index of a new Providers subsection of the navigation, which will likely contain other pages.
Lastly, this adjusts the navigation wording of resource pages for active voice consistency.
=> website: Create concept-specific configuration validation pages

website/docs/plugin/framework/accessing-values.mdx, website/docs/plugin/framework/writing-state.mdx
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/498
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/418
Reference: https://discuss.hashicorp.com/t/terraform-plan-does-not-allow-sending-only-delta-for-list-type-parameters-in-the-resource-block/45027
Reference: https://discuss.hashicorp.com/t/set-state-for-optional-nested-attributes-for-singlenestedattributes/44838
Reference: https://discuss.hashicorp.com/t/why-is-req-plan-get-in-my-create-method-throwing-an-error/44441
Reference: https://discuss.hashicorp.com/t/terraform-plugin-framework-value-conversion-error-unhandled-unknown-value/44382
... plenty more ...
The current recommendation is now to always use `types` package types, unless there is no chance for null/unknown values. The …
=> website: Further discourage usage of non-types package types with accessing schema data

website/docs/plugin/framework/resources/plan-modification.mdx
Reference: https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/resource#ModifyPlanRequest
Reference: https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/resource#ModifyPlanResponse
This was missed when the `resource` package was initially created.
=> website: Fix old code examples to tfsdk.ModifyResourcePlanRe(quest|sponse)

website/data/plugin-framework-nav-data.json, website/docs/plugin/framework/index.mdx
Collection will be published soon.
=> website: Update HashiCorp learn links for new collection

website/docs/plugin/framework/migrating/attributes-blocks/blocks-computed.mdx, website/docs/plugin/framework/migrating/attributes-blocks/types.mdx, website/docs/plugin/framework/migrating/attributes-blocks/validators-predefined.mdx, website/docs/plugin/framework/migrating/resources/import.mdx, website/docs/plugin/framework/provider-servers.mdx
This rewrites some markdown links to be their final redirect destinations.
This is in support of the GA Rollout to developer.hashicorp.com
=> chore(docs): rewrite internal redirects

website/docs/plugin/framework/migrating/attributes-blocks/validators-custom.mdx, website/docs/plugin/framework/migrating/attributes-blocks/validators-predefined.mdx, website/docs/plugin/framework/migrating/providers/index.mdx, website/docs/plugin/framework/migrating/resources/plan-modification.mdx
Broken links are a bad user experience - this PR fixes some that we found in the latest review of devdot! :)
=> fix broken links

tfsdk/config.go, tfsdk/plan.go, tfsdk/state.go, website/docs/plugin/framework/accessing-values.mdx, website/docs/plugin/framework/writing-state.mdx
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/66
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/186
Documenting existing intentions and behaviors with `tfsdk.Config`, `tfsdk.Plan`, and `tfsdk.State` type `GetAttribute()` and `SetAttribute()` methods.
=> tfsdk: Document and clarify GetAttribute and SetAttribute further

website/data/plugin-framework-nav-data.json, website/docs/plugin/framework/resources/create.mdx, website/docs/plugin/framework/resources/delete.mdx, website/docs/plugin/framework/resources/index.mdx, website/docs/plugin/framework/resources/read.mdx, website/docs/plugin/framework/resources/update.mdx
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/258
Closes #527
Each lifecycle operation has its own set of caveats, recommendations, and specific use cases. These individualized pages will clarify and enable the additional documentation requirements. This change also adds update documentation to show how to determine whether an individual attribute value was changed during update, to show the new layout in action.
=> website: Split resource lifecycle management into separate pages

.changelog/536.txt, internal/fwserver/attr_value.go, internal/fwserver/attribute_plan_modification.go, internal/fwserver/attribute_plan_modification_test.go, internal/fwserver/attribute_validation.go, internal/fwserver/attribute_validation_test.go, internal/fwserver/block_plan_modification.go, internal/fwserver/block_plan_modification_test.go, internal/fwserver/block_validation.go, internal/testing/types/listnestedattributescustom.go, internal/testing/types/mapnestedattributescustom.go, internal/testing/types/setnestedattributescustom.go, internal/testing/types/singlenestedattributescustom.go, types/bool.go, types/float64.go, types/int64.go, types/list.go, types/map.go, types/number.go, types/object.go, types/primitive.go, types/set.go, types/string.go
=> types: Add Typable and Valuable Interfaces

internal/fwserver/server_planresourcechange_test.go
Relates #483 
Relates https://github.com/hashicorp/terraform-provider-corner/pull/89
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27857 (acceptance tests pass after this fix)
`MarkComputedNilsAsUnknown` now passes block values through unmodified, rather than throwing an error. 
I extended the single large test object to add block attributes, but I can also split into individual test cases if that'd be helpful. Original issue is reproduced with the updated test case and the fix commented out:
```console
$ go test -count=1 -run "^TestMarkComputedNilsAsUnknown$" ./internal/fwserver/...
--- FAIL: TestMarkComputedNilsAsUnknown (0.00s)
server_planresourcechange_test.go:283: Unexpected error: AttributeName("block-nil-optional-computed"): couldn't find attribute in resource …
```
=> Skip blocks while marking computed nils unknown

.changelog/548.txt, datasource/schema/schema.go, datasource/schema/schema_test.go, internal/fwschema/schema.go, internal/fwserver/server.go, internal/fwserver/server_getproviderschema_test.go, provider/metaschema/schema.go, provider/metaschema/schema_test.go, provider/schema/schema.go, provider/schema/schema_test.go, resource/schema/schema.go, resource/schema/schema_test.go
Closes: #136
Once all references to `tfsdk.Schema` have been removed we can ammend `fwschema/schema.go`:
```go
type Schema interface {
/* ... */
Validate() diag.Diagnostics
}
```
=> Fix Framework allows top-level schema attributes that conflict with Terraform meta-arguments

website/docs/plugin/framework/resources/plan-modification.mdx
While testing out the documentation for creating a default value my LSP informed me that there was no field `AttributePlan` and upon checking the relevant type I found there was a `PlanValue` which seems to be what should be referenced in the example code.
=> fix incorrect field reference

website/docs/plugin/framework/migrating/index.mdx
The overview page tries to hint that muxing can be used to iteratively migrate providers from SDK to framework, however the current link points to the generic mux documentation. The migration guide providers page has excellent content that is specific for this situation so it seems ideal to point there (which also links out to the generic mux documentation) rather than giving developers less directly useful information.
=> website: Point overview muxing link at migration guide content

.golangci.yml, datasource/schema/schema_test.go, diag/diagnostics_test.go, internal/privatestate/data_test.go, internal/reflect/struct_test.go, provider/metaschema/schema_test.go, provider/schema/schema_test.go, providerserver/providerserver_test.go, resource/schema/schema_test.go, types/basetypes/list_test.go, types/basetypes/map_test.go
Reference: https://github.com/kunwardeep/paralleltest
The upstream issue with map-based `range` false positives appears to be resolved.
=> ci: Enable paralleltest linter

internal/fwserver/schema_validation.go, internal/fwserver/server_validatedatasourceconfig.go, internal/fwserver/server_validateproviderconfig.go, internal/fwserver/server_validateresourceconfig.go
More info here: hashicorp/terraform-plugin-framework-validators#94
Basically, it just makes sure the validators cannot accidentally drop previous diags.
=> Prevent validators from dropping diags

.changelog/619.txt, internal/fwserver/server_validatedatasourceconfig_test.go, internal/fwserver/server_validateproviderconfig_test.go, internal/fwserver/server_validateresourceconfig_test.go
Reference: https://github.com/hashicorp/terraform-plugin-framework/pull/619
Against current `main`:
```
--- FAIL: TestServerValidateDataSourceConfig (0.00s)
--- FAIL: TestServerValidateDataSourceConfig/request-config-DataSourceWithConfigValidators-diagnostics (0.00s)
/Users/bflad/src/github.com/hashicorp/terraform-plugin-framework/internal/fwserver/server_validatedatasourceconfig_test.go:301: unexpected difference:   &fwserver.ValidateDataSourceConfigResponse{
- 	Diagnostics: diag.Diagnostics{diag.ErrorDiagnostic{detail: "error detail 2", summary: "error summary 2"}},
+ 	Diagnostics: diag.Diagnostics{
+ 		diag.ErrorDiagnostic{detail: "error detail 1", summary: "error summary 1"},
+ 		diag.ErrorDiagnostic{detail: "error detail 2", summary: "error summary 2"},
+ 	},
  }
--- FAIL: …
```
=> internal/fwserver: Unit testing and changelog for ConfigValidators diagnostics overwrites

.golangci.yml, website/docs/plugin/framework/getting-started/code-walkthrough.mdx, website/docs/plugin/framework/migrating/attributes-blocks/types.mdx
- Added `misspell`, ref https://github.com/hashicorp/terraform-providers-devex-internal/issues/83
- I decided to not add `forcetypeassert` in this PR as it had a number of hits:
<details>
<summary>
</summary>
```bash
$ golangci-lint run
internal/reflect/interfaces_test.go:272:4: type assertion must be checked (forcetypeassert)
got := res.Interface().(*unknownableString)
^
internal/reflect/interfaces_test.go:370:4: type assertion must be checked (forcetypeassert)
got := res.Interface().(*nullableString)
^
internal/reflect/interfaces_test.go:460:4: type assertion must be checked (forcetypeassert)
got := res.Interface().(types.String)
^
internal/reflect/interfaces_test.go:557:4: type assertion must be checked (forcetypeassert)
got := res.Interface().(*valueConverter)
^ …
```
=> Added lint rule + fix broken doc links

.golangci.yml, internal/fwschemadata/data_get_at_path.go, internal/fwserver/server_createresource.go, internal/fwserver/server_deleteresource.go, internal/fwserver/server_importresourcestate.go, internal/fwserver/server_planresourcechange.go, internal/fwserver/server_readdatasource.go, internal/fwserver/server_readresource.go, internal/fwserver/server_updateresource.go, internal/fwserver/server_upgraderesourcestate.go, internal/fwserver/server_validatedatasourceconfig.go, internal/fwserver/server_validateresourceconfig.go, internal/reflect/interfaces_test.go, internal/reflect/pointer_test.go, internal/reflect/pointer_zero_test.go, internal/testing/types/boolwithvalidate.go, internal/testing/types/numberwithvalidate.go, internal/testing/types/stringwithvalidate.go, tfsdk/value_as.go, tfsdk/value_as_test.go
contributes to: https://github.com/hashicorp/terraform-providers-devex-internal/issues/102
I used the surrounding code's context as clues to how to handle the type assertions, lmk if there are more appropriate ways to handle them.
=> ci: added `forcetypeassert` lint rule + resolved all lint warnings

attr/type.go, attr/value.go, types/basetypes/list.go, types/basetypes/map.go, types/basetypes/object.go, types/basetypes/set.go
Closes #679
This documentation may have stemmed from an early design goal to include semantic equality within types. The initial implementation did not include that functionality, which is being tracked with https://github.com/hashicorp/terraform-plugin-framework/issues/70.
=> attr: Fix verbiage for Type and Value type Equal methods

.github/CONTRIBUTING.md
This also cleans up the changelog management and releases sections.
=> .github: Contributing guide updates to clarify current stances and recommendations

.changes/unreleased/ENHANCEMENTS-20230330-105617.yaml, .changes/unreleased/ENHANCEMENTS-20230330-105618.yaml, .changes/unreleased/ENHANCEMENTS-20230330-105619.yaml, internal/fwschema/attribute_name_validation.go, internal/fwschema/attribute_name_validation_test.go
Closes #705
The error diagnostic details will only contain this additional context if a numeric is detected.
=> internal/fwschema: Validate leading numerics in attribute names

.changes/unreleased/BUG FIXES-20230404-211215.yaml, internal/reflect/interfaces.go, internal/reflect/interfaces_test.go, internal/reflect/struct.go, internal/reflect/struct_test.go
Closes #566
Previously in a provider where a `types.Object` zero value was used in `(tfsdk.State).Set()`:
```
panic: AttributeName("single_nested_attribute"): can't use tftypes.Object[] as tftypes.Object["nested_attribute":tftypes.String]
goroutine 448 [running]:
github.com/hashicorp/terraform-plugin-go/tftypes.NewValue(...)
/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.3/tftypes/value.go:273
github.com/hashicorp/terraform-plugin-framework/internal/reflect.FromStruct({0x1035b3e40, 0x140001fa870}, {0x1035b86f8?, 0x140001faae0?}, {0x103504480?, 0x140001ff400?, 0x10b4975c8?}, {{0x103b8fc60?, 0x50?, 0x1400006c900?}})
/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/reflect/struct.go:207 +0x73c …
```
=> internal/reflect: Raise framework errors instead of upstream errors or panics with mismatched types

.changes/unreleased/BUG FIXES-20230406-112757.yaml, internal/fwserver/attribute_plan_modification_test.go, internal/fwserver/block_plan_modification_test.go, internal/fwserver/schema_plan_modification_test.go, internal/parentpath/doc.go, internal/parentpath/has_list_or_set.go, internal/parentpath/has_list_or_set_test.go, internal/planmodifierdiag/doc.go, internal/planmodifierdiag/use_state_for_unknown.go, internal/planmodifierdiag/use_state_for_unknown_test.go, resource/schema/boolplanmodifier/use_state_for_unknown.go, resource/schema/boolplanmodifier/use_state_for_unknown_test.go, resource/schema/float64planmodifier/use_state_for_unknown.go, resource/schema/float64planmodifier/use_state_for_unknown_test.go, resource/schema/int64planmodifier/use_state_for_unknown.go, resource/schema/int64planmodifier/use_state_for_unknown_test.go, resource/schema/listplanmodifier/use_state_for_unknown.go, resource/schema/listplanmodifier/use_state_for_unknown_test.go, resource/schema/mapplanmodifier/use_state_for_unknown.go, resource/schema/mapplanmodifier/use_state_for_unknown_test.go, resource/schema/numberplanmodifier/use_state_for_unknown.go, resource/schema/numberplanmodifier/use_state_for_unknown_test.go, resource/schema/objectplanmodifier/use_state_for_unknown.go, resource/schema/objectplanmodifier/use_state_for_unknown_test.go, resource/schema/setplanmodifier/use_state_for_unknown.go, resource/schema/setplanmodifier/use_state_for_unknown_test.go, resource/schema/stringplanmodifier/use_state_for_unknown.go, resource/schema/stringplanmodifier/use_state_for_unknown_test.go, website/docs/plugin/framework/resources/plan-modification.mdx
Closes #709
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/717
This change will adjust the `UseStateForUnknown` plan modifiers to return an implementation error if defined on an attribute below a list or set. In any cases where the list or set elements were rearranged or removed, the plan modifier result could cause invalid data being proposed in the plan or Terraform data consistency errors. These situations require additional value identifying information from the provider developer to ensure that the prior state for an element is correctly realigned, however the `UseStateForUnknown` plan modifier takes no parameters for such information and adding those parameters would represent a breaking change to the function signature. Future framework proposals will …
=> resource/schema: Prevent UseStateForUnknown data misalignment by raising implementation error when under a list or set

website/docs/plugin/framework/migrating/schema/index.mdx
👋 Hi there,
I was browsing the docs and found these two broken links
Old links that 404:
- [https://developer.hashicorp.com/terraform/plugin/framework/migrating/attributes-**and**-blocks/attribute-schema](https://developer.hashicorp.com/terraform/plugin/framework/migrating/attributes-and-blocks/attribute-schema)
- [https://developer.hashicorp.com/terraform/plugin/framework/migrating/attributes-**and**-blocks/blocks](https://developer.hashicorp.com/terraform/plugin/framework/migrating/attributes-and-blocks/blocks)
New links:
- https://developer.hashicorp.com/terraform/plugin/framework/migrating/attributes-blocks/attribute-schema
- https://developer.hashicorp.com/terraform/plugin/framework/migrating/attributes-blocks/blocks
=> Correct broken URLs describing attributes+blocks

website/docs/plugin/framework/validation.mdx
Fixing the typo in the document.
`tftypes` doesn't have `ValueAs` function. This should be replaced by `tfsdk.ValueAs` from `terraform-plugin-framework@v1.2.0`
=> Update tftypes  -> tfsdk in validation.mdx

.github/dependabot.yml, .github/workflows/compliance.yml
- Missed adding the `tools` folder to dependabot in #745
- Ensures that an error is thrown if the license is malformed or missing
=> Add `tools` folder to dependabot and add license dry run flag

.changes/unreleased/BUG FIXES-20230609-162628.yaml, internal/reflect/struct_test.go, types/basetypes/list_type.go, types/basetypes/list_type_test.go, types/basetypes/map_type.go, types/basetypes/map_type_test.go, types/basetypes/missing_type.go, types/basetypes/missing_value.go, types/basetypes/object_type_test.go, types/basetypes/set_type.go, types/basetypes/set_type_test.go
Closes #714
Previously before logic updates:
```
--- FAIL: TestListTypeString (0.00s)
--- FAIL: TestListTypeString/ElemType-missing (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x102ff0068]
goroutine 19 [running]:
testing.tRunner.func1.2({0x1030efe00, 0x1032e7b10})
/opt/homebrew/Cellar/go/1.20.5/libexec/src/testing/testing.go:1526 +0x1c8
testing.tRunner.func1()
/opt/homebrew/Cellar/go/1.20.5/libexec/src/testing/testing.go:1529 +0x384
panic({0x1030efe00, 0x1032e7b10})
/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/panic.go:884 +0x204
github.com/hashicorp/terraform-plugin-framework/types/basetypes.ListType.Str …
```
=> types/basetypes: Prevent panics in `ListType`, `MapType`, and `SetType` methods when `ElemType` field is not set

internal/fwschema/nested_attribute.go
Follow-up to #753 
Adjusts the `NestedAttributesEqual` method to perform the compare on the "shallow" portions of the attribute before comparing the nested attributes, similar to `BlocksEqual`: https://github.com/hashicorp/terraform-plugin-framework/blob/532797d138849d5b4404b7711157f360fe0decc2/internal/fwschema/block.go#L71
=> Adjust `NestedAttributesEqual` to perform shallow compare first

website/docs/plugin/framework/handling-data/custom-types.mdx
This quick change will bring the type embedding override lists for schema and value types closer to the example code. It also adjusts the wording of "should be overridden" to "must be overridden" to try to help prevent confusing situations or error messages.
=> docs: Adjust semantic equality ordering and use stronger wording for overriding methods

internal/fwserver/server_planresourcechange_test.go
Reference: https://github.com/hashicorp/terraform-plugin-framework/pull/715
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/754
This adjusts the existing `PlanResourceChange` unit testing for schema-based default value handling to include a test case of an attribute with both `CustomType` and `Default` set. The framework now performs stricter value type checking and this test case can act as a canary should the framework's storage of data from Terraform be migrated to the framework type system. The testing passes as-is, unlike the original case of both `CustomType` and `PlanModifiers` being set after the validation logic introduction because the default value handling occurs in the underlying terraform-plugin-go type system so there is no need to re-instantiate …
=> internal/fwserver: Add unit test for PlanResourceChange with CustomType and Default

.changes/unreleased/BUG FIXES-20230703-123518.yaml, types/basetypes/object_value.go, types/basetypes/object_value_test.go
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/775
The prior implementation used the exported `AttributeTypes()` method, which in this case was unnecessarily creating a copy of the map when it was only be used for walking the existing data. At scale, such as handling 1000+ objects, this creates unnecessary pressure on the Go garbage collector.
`benchstat` comparison with new benchmark test:
```text
goos: darwin
goarch: arm64
pkg: github.com/hashicorp/terraform-plugin-framework/types/basetypes
│  original   │              proposed               │
│   sec/op    │   sec/op     vs base                │
ObjectValueToTerraformValue1000-10   408.4µ ± 1%   318.4µ ± 1%  -22.02% (p=0.000 n=10)
│   original   │               proposed               │
│     B/op     │ …
```
=> types/basetypes: Reduce memory allocations of (ObjectValue).ToTerraformValue()

internal/reflect/helpers_test.go, internal/reflect/struct_test.go
This PR will make it easier for us to verify internal refactoring that is made to any of the struct reflection logic. That includes:
- Moving the existing `Struct` error tests into a single table-driven test (same as `FromStruct`)
- Moving all the internal testing of `getStructTags` to use the exported `Struct` method
- The only test that was removed was `TestGetStructTags_notAStruct`, as the exported methods (`FromStruct` & `Struct`) already have tests for this scenario and the logic in `getStructTags` is mostly defensive.
- Added new tests to `FromStruct` for all the error scenarios from `getStructTags` + the success scenario with ignored tags
=> internal/reflection: Migrate reflection tests for struct tags to exported methods

.changes/unreleased/BUG FIXES-20230711-161747.yaml, internal/fwschemadata/data_get_at_path_test.go, internal/fwserver/server_planresourcechange.go, internal/fwserver/server_planresourcechange_test.go
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/783
Prior to the logic update:
```
--- FAIL: TestServerPlanResourceChange (0.01s)
--- FAIL: TestServerPlanResourceChange/update-set-default-values (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1043b0484]
goroutine 32 [running]:
testing.tRunner.func1.2({0x1048d4e60, 0x104c08f90})
/opt/homebrew/Cellar/go/1.20.5/libexec/src/testing/testing.go:1526 +0x1c8
testing.tRunner.func1()
/opt/homebrew/Cellar/go/1.20.5/libexec/src/testing/testing.go:1529 +0x384
panic({0x1048d4e60, 0x104c08f90}) …
```
=> internal/fwserver: Prevent PlanResourceChange panic during changed path logging

internal/fwserver/server_planresourcechange.go
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/183
When plan modification logic was introduced into the framework, it was not clear whether a multiple pass approach to running provider logic would be necessary. After thorough investigation, the multiple pass approach was instead replaced with explicit attribute default functionality to cover the main use case for such an approach, but the code comments were not removed when that was completed. To prevent future maintainer confusion, this is removing the old code comments.
=> internal/fwserver: Remove old multiple pass code comments in PlanResourceChange logic

.changes/unreleased/BUG FIXES-20230719-142413.yaml, internal/reflect/interfaces.go, internal/reflect/interfaces_test.go, internal/reflect/struct_test.go
Reference: https://github.com/hashicorp/terraform-plugin-framework/pull/715
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/793
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/32441
The original intention of this logic was to raise a framework error instead of underlying terraform-plugin-go error or panic when providers returned an errant value from their logic. In practice though, comparing the framework types (which may include either base or custom types) was too strict. Technically, as long as the underlying terraform-plugin-go types are equivalent, then this check should pass. Terraform will catch any errant modifications of the actual values, should there be a difference between the base types and custom types.
=> internal/reflect: Use underlying terraform-plugin-go types to validate provider given values

website/docs/plugin/framework/handling-data/attributes.mdx
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/805
=> docs: Use arbitrary with map keys and explicit with object attribute names

website/docs/plugin/framework/handling-data/attributes.mdx, website/docs/plugin/framework/handling-data/custom-types.mdx
This PR tweaks some of the custom type documentation and adds links to the new common custom type package docs.
- Closes #786 with additional clarification on `Equal` vs `*SemanticEquals` method
=> website/docs: Update documentation to reflect new common custom types

.changes/unreleased/BUG FIXES-20230803-120411.yaml, types/basetypes/float64_type.go, types/basetypes/float64_type_test.go, types/basetypes/float64_value.go, types/basetypes/float64_value_test.go
Closes #815 
Related corner tests: https://github.com/hashicorp/terraform-provider-corner/pull/170
Terraform core's `number` type can store up to [512 bits of precision](https://github.com/zclconf/go-cty/blob/main/docs/types.md#ctynumber) for floating numbers. This level of precision is typically only encountered when performing an arithmetic operation like below:
```bash
$ terraform console
> 1 - 0.99
0.010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003
```
The `Float64Attribute` underlying value of Go's built-in `float64` type was losing this precision and responding with invalid plan value errors seen in #815 .
This PR replaces the underlying value of `Float64Attribute` with a …
=> types/basetypes: Fix Float64Attribute precision comparisons

.changes/unreleased/NOTES-20230803-173432.yaml, .changes/unreleased/NOTES-20230803-173640.yaml, .github/CONTRIBUTING.md, internal/fwschemadata/data_set_at_path.go, internal/fwschemadata/data_value.go, internal/fwserver/attribute_plan_modification.go, internal/fwserver/attribute_validation.go, internal/fwserver/block_plan_modification.go, internal/fwserver/block_validation.go, internal/fwserver/server.go, internal/fwserver/server_configureprovider.go, internal/fwserver/server_createresource.go, internal/fwserver/server_deleteresource.go, internal/fwserver/server_getproviderschema.go, internal/fwserver/server_importresourcestate.go, internal/fwserver/server_planresourcechange.go, internal/fwserver/server_readdatasource.go, internal/fwserver/server_readresource.go, internal/fwserver/server_updateresource.go, internal/fwserver/server_upgraderesourcestate.go, internal/fwserver/server_validatedatasourceconfig.go, internal/fwserver/server_validateproviderconfig.go, internal/fwserver/server_validateresourceconfig.go, internal/proto5server/server_getproviderschema_test.go, internal/proto6server/server_getproviderschema_test.go
Closes #812 
Per https://developer.hashicorp.com/terraform/plugin/log/managing#log-levels, moving these logs to `TRACE` as these messages define where the provider code is at in execution.
=> internal: Update all provider defined method call logs to TRACE

website/docs/plugin/framework/acctests.mdx
Reference: https://github.com/hashicorp/terraform-plugin-testing/issues/84
terraform-plugin-testing version 1.5.0 and later will no longer require managed resources and data resources to implement the `id` attribute.
=> website: Move acceptance testing id requirement to troubleshooting section

website/docs/plugin/framework/migrating/index.mdx, website/docs/plugin/framework/migrating/resources/crud.mdx, website/docs/plugin/framework/migrating/resources/index.mdx
Related SDKv2 docs: https://github.com/hashicorp/terraform-plugin-sdk/pull/1232
This PR adds a section to the CRUD migration page describing how to utilize a custom type to resolve the `planned value does not match config value` data consistency error from SDKv2.
=> website: Add data consistency error migration docs for "planned value does not match config value"

website/docs/plugin/framework/handling-data/attributes/list-nested.mdx, website/docs/plugin/framework/handling-data/attributes/map-nested.mdx, website/docs/plugin/framework/handling-data/attributes/set-nested.mdx
The PR fixes some typos in the documentation related to NestedAttributeObject.
=> Typo in documentation related to NestedAttributeObject

website/docs/plugin/framework/handling-data/attributes/bool.mdx, website/docs/plugin/framework/handling-data/attributes/float64.mdx, website/docs/plugin/framework/handling-data/attributes/int64.mdx, website/docs/plugin/framework/handling-data/attributes/list-nested.mdx, website/docs/plugin/framework/handling-data/attributes/list.mdx, website/docs/plugin/framework/handling-data/attributes/map-nested.mdx, website/docs/plugin/framework/handling-data/attributes/map.mdx, website/docs/plugin/framework/handling-data/attributes/number.mdx, website/docs/plugin/framework/handling-data/attributes/object.mdx, website/docs/plugin/framework/handling-data/attributes/set-nested.mdx, website/docs/plugin/framework/handling-data/attributes/set.mdx, website/docs/plugin/framework/handling-data/attributes/single-nested.mdx, website/docs/plugin/framework/handling-data/attributes/string.mdx, website/docs/plugin/framework/handling-data/blocks/list-nested.mdx, website/docs/plugin/framework/handling-data/blocks/set-nested.mdx, website/docs/plugin/framework/handling-data/blocks/single-nested.mdx
Fixes locations where the incorrect reference `terraform/plugin/framework/handing-data/writing-state` is used, replaced with the correct `terraform/plugin/framework/handling-data/writing-state`.
=> Correct Site Doc Links To "Write State" Page

.changes/unreleased/BUG FIXES-20231023-165712.yaml, .changes/unreleased/BUG FIXES-20231023-165814.yaml, internal/fwserver/server_applyresourcechange_test.go, internal/fwserver/server_deleteresource.go, internal/fwserver/server_deleteresource_test.go, internal/proto5server/server_applyresourcechange_test.go, internal/proto6server/server_applyresourcechange_test.go, resource/delete.go
Closes #863
The previous implementation assumed that Terraform core would preserve private state similar to "regular" state when a provider returned an error diagnostic while destroying a resource. The core implementation instead always uses the response data, which the framework was previously always discarding. This change corrects the errant design while also enabling provider logic to potentially update the private state in this situation.
=> resource: Prevent private state data loss on Delete method error

.changes/unreleased/FEATURES-20231102-160132.yaml, internal/fromtftypes/value_test.go, internal/reflect/interfaces_test.go, internal/reflect/into_test.go, internal/reflect/outof_test.go, internal/reflect/slice.go, types/basetypes/tuple_type.go, types/basetypes/tuple_type_test.go, types/basetypes/tuple_value.go, types/basetypes/tuple_value_test.go, types/tuple_type.go, types/tuple_value.go, website/data/plugin-framework-nav-data.json, website/docs/plugin/framework/handling-data/types/index.mdx, website/docs/plugin/framework/handling-data/types/list.mdx, website/docs/plugin/framework/handling-data/types/set.mdx, website/docs/plugin/framework/handling-data/types/tuple.mdx
Ref: #54 
This PR introduces `basetypes.TupleType`, `basetypes.TupleValue`, and tuple helper functions/aliases in the `types` package. This PR **does not** introduce any accompanying `TupleAttribute` implementations, so currently there is no way to describe this schema to Terraform core.
Eventually when #147 is implemented, the `TupleType` will be necessary to fully handle dynamic attributes, as then Terraform core could possible send a [tuple](https://developer.hashicorp.com/terraform/language/expressions/type-constraints#tuple) to Plugin Framework.
- I updated the reflection rules to create an explicit message describing that reflection from Go slices into `types.Tuple` is not supported. Also added tests around the code that was refactored relating to sets/lists
- There weren't explicit …
=> types/basetypes: Add Tuple type support

website/docs/plugin/framework/migrating/testing.mdx
Related: #875
This PR updates the example in the documentation for testing migrations to emphasise that this form of testing is typically limited to managed resources.
=> Updating documentation for testing migration

website/docs/plugin/framework/migrating/testing.mdx
Closes #875
The purpose of this additional documentation is two-fold:
- Showing how to perform migration testing of full data source data, using the `terraform_data` managed resource
- Recommending that developers should instead prefer individual attribute value testing for data sources
=> docs: Further clarify SDK migration testing of data sources

website/docs/plugin/framework/migrating/testing.mdx
Reference: https://github.com/hashicorp/terraform-plugin-testing/issues/256
=> website: Use ConfigPlanChecks instead of PlanOnly in migration testing

website/docs/plugin/framework/resources/read.mdx, website/docs/plugin/framework/resources/state-upgrade.mdx
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/902
Reference: https://github.com/hashicorp/terraform/issues/34502
Reference: https://github.com/hashicorp/terraform/issues/34503
Unknown values are never valid in resource state and while Terraform nor the framework actually raise these errors right now, one or both will in the near future. This documents the errant implementation detail for developers in the meantime since it otherwise causes confusing Terraform behaviors for practitioners.
=> website: Document managed resource Read and UpgradeState unknown value errors

website/docs/plugin/framework/functions/parameters/index.mdx, website/docs/plugin/framework/functions/returns/index.mdx
Apparently the issue I recreated locally was not the caching problem, but actual broken links 😆
=> website: Fixed function doc links in parameter/return sections

.changes/unreleased/ENHANCEMENTS-20240126-073810.yaml, internal/privatestate/data.go, internal/privatestate/data_test.go, website/docs/plugin/framework/resources/private-state.mdx
Closes #910
This change ensures that developers can fully remove private state keys by setting the value to `nil` or `[]byte{}`. Attempting to set the value to either value would previously generate an error. The closest available workaround was to set keys to the literal JSON `null` and handle that value during unmarshaling, rather than purely checking existence via `GetKey()` returning `nil`.
=> privatestate: Support nil or zero-length value in SetKey to remove key

.changes/unreleased/FEATURES-20240201-173428.yaml, internal/fromproto5/moveresourcestate.go, internal/fromproto5/moveresourcestate_test.go, internal/fromproto6/moveresourcestate.go, internal/fromproto6/moveresourcestate_test.go, internal/fwserver/server_capabilities.go, internal/fwserver/server_getmetadata_test.go, internal/fwserver/server_getproviderschema_test.go, internal/fwserver/server_moveresourcestate.go, internal/fwserver/server_moveresourcestate_test.go, internal/fwserver/server_upgraderesourcestate.go, internal/proto5server/server_moveresourcestate.go, internal/proto5server/server_moveresourcestate_test.go, internal/proto6server/server_moveresourcestate.go, internal/proto6server/server_moveresourcestate_test.go, internal/testing/testprovider/resourcewithmovestate.go, internal/toproto5/moveresourcestate.go, internal/toproto5/moveresourcestate_test.go, internal/toproto6/moveresourcestate.go, internal/toproto6/moveresourcestate_test.go, resource/move_state.go, resource/resource.go, resource/state_mover.go, website/data/plugin-framework-nav-data.json, website/docs/plugin/framework/resources/state-move.mdx
This change adds initial support for the `MoveResourceState` RPC to the framework, including:
* Adding the framework shared server implementation for the new RPC
* Adding the protocol version 5 and 6 server implementations for the new RPC
* Adding the type conversion logic for the framework types to/from the protocol types
* Exposing a new `resource.ResourceWithMoveState` interface that providers can implement to support the new RPC
* Adding a website documentation page for the new functionality
A state move using the new RPC occurs when a Terraform 1.8 and later configuration includes a `moved` configuration block such as the following:
```terraform
moved {
from = "examplecloud_source.XXX"
to   = "examplecloud_target.XXX"
}
```
There are no restrictions on the source resource types, but …
=> resource: Initial MoveResourceState RPC support

.changes/unreleased/BREAKING CHANGES-20240216-142501.yaml, .changes/unreleased/NOTES-20240216-090121.yaml, function/arguments_data.go, function/arguments_data_test.go, function/definition.go, internal/fromproto5/arguments_data.go, internal/fromproto5/arguments_data_test.go, internal/fromproto6/arguments_data.go, internal/fromproto6/arguments_data_test.go, internal/fwserver/server_callfunction_test.go, internal/proto5server/server_callfunction_test.go, internal/proto6server/server_callfunction_test.go, internal/reflect/into_test.go, internal/reflect/outof_test.go, internal/reflect/slice.go, path/path.go, path/path_test.go, website/docs/plugin/framework/functions/implementation.mdx, website/docs/plugin/framework/handling-data/types/tuple.mdx
This PR contains a breaking change to provider-defined function handling for variadic parameters, switching the framework type representation from `types.List` to `types.Tuple`, where each element is the same element type.
If provider developers are utilizing slice reflection to retrieve variadic argument values, there will be no changes required due to the updates to support tuple reflection, noted below in `Reflection Changes`:
```go
func (f *ExampleFunction) Run(ctx context.Context, req function.RunRequest, resp *function.RunResponse) {
var boolArg bool
var stringVarg []string
// Despite being a tuple[string,string,etc.] under the hood, reflection will still work here
resp.Diagnostics.Append(req.Arguments.Get(ctx, &boolArg, &stringVarg)...)
}
```
Initially, we grouped all variadic …
=> function: Switch the representation of variadic arguments to `types.Tuple`

internal/reflect/number.go, internal/reflect/number_test.go, internal/reflect/options.go
=> reflect: Determine equivalency of float32 or float64, and *big.Float via string representation  

diag/diagnostics.go
=> fix: remove incorrect code in `Diagnostics.Append` - fixes #932

.changes/unreleased/BUG FIXES-20240228-103338.yaml, internal/fwschema/diagnostics.go, internal/fwschemadata/data_default.go, internal/fwschemadata/data_default_test.go, resource/schema/list_attribute.go, resource/schema/list_attribute_test.go, resource/schema/list_nested_attribute.go, resource/schema/list_nested_attribute_test.go, resource/schema/map_attribute.go, resource/schema/map_attribute_test.go, resource/schema/map_nested_attribute.go, resource/schema/map_nested_attribute_test.go, resource/schema/object_attribute.go, resource/schema/object_attribute_test.go, resource/schema/set_attribute.go, resource/schema/set_attribute_test.go, resource/schema/set_nested_attribute.go, resource/schema/set_nested_attribute_test.go, resource/schema/single_nested_attribute.go, resource/schema/single_nested_attribute_test.go
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/590
Closes #930
Previously the logic handling attribute `Default` values would silently ignore any type errors, which would lead to confusing planning data behaviors. This updates the logic to raise those error properly and adds covering unit testing.
These error messages are using the underlying `tftypes` type system errors which is currently a pragmatic compromise throughout various parts of the framework logic that bridges between both type systems to save additional type assertion logic and potential bugs relating to those conversions. In the future if the internal `tftypes` handling and exported fields are replaced with the framework type system types, this logic would instead return error messaging based on …
=> resource/schema: Ensure invalid attribute default value errors are raised

website/docs/plugin/framework/functions/testing.mdx
Closes https://github.com/hashicorp/terraform-plugin-framework/issues/928
Please see the issue above for context about the nil pointer error.
=> Update provider functions testing docs to help users avoid nil pointer error

.changes/unreleased/NOTES-20240229-142101.yaml, .github/workflows/ci-go.yml, README.md, go.mod, tools/go.mod, tools/go.sum, website/docs/plugin/framework/migrating/index.mdx
Reference: https://github.com/hashicorp/terraform-providers-devex-internal/issues/175
- Adding a change log entry for the bump to Go `1.21`.
- Reinstating the `go toolchain` directive in `go.mod`.
- Updating CI and docs to reflect update to Go `1.21`.
=> Reinstate go toolchain and add changelog for Go version bump to 1.21

website/docs/plugin/framework/validation.mdx
Fixing documentation in code sample used for [Defining Type Validation](https://developer.hashicorp.com/terraform/plugin/framework/validation#defining-type-validation).
**Before**:
```go
func (t computeInstanceIdentifierType) Validate(ctx context.Context, tfValue tftypes.Value, path path.Path) diag.Diagnostics {
var diags diag.Diagnostics
if !tfValue.Type().Equal(tftypes.String) {
diags.AddAttributeError(
path,
"Compute Instance Type Validation Error",
fmt.Sprintf("Expected String value, received %T with value: %v", in, in),
/* ... */
```
**After**:
```go
func (t computeInstanceIdentifierType) Validate(ctx context.Context, tfValue tftypes.Value, path path.Path) diag.Diagnostics {
var diags diag.Diagnostics
if !tfValue.Type().Equal(tftypes.String) {
diags.AddAttributeError(
path,
"Compute …
```
=> Fixing Documentation for Defining Type Validation

website/docs/plugin/framework/functions/testing.mdx
Provider-defined functions are only supported in Terraform 1.8 and later. Provider developers that run acceptance testing across multiple Terraform versions will likely want to know how to setup their tests to avoid test failures in earlier versions of Terraform.
The terraform-plugin-testing v1.7.0 release earlier this week contains the `tfversion.Version1_8_0` variable which makes this setup easier. Other recent terraform-plugin-testing versions support the `TerraformVersionChecks` handling, although developers would need to "manually" create the version with `go-version` via `version.Must(version.NewVersion("1.8.0"))`.
=> docs: Include tfversion checking in function acceptance testing

website/docs/plugin/framework/data-sources/configure.mdx, website/docs/plugin/framework/resources/configure.mdx
Reference: https://github.com/hashicorp/tutorials/issues/1944
Updating documentation to clarify that a `nil` check of `ProviderData` should always be performed in the `Configure()` method of data sources and resources.
=> Add clarification for nil check of ProviderData in data source and resource Configure() method

website/docs/plugin/framework/functions/index.mdx
Stumbled across this when I was writing some docs, follow-up to #946
=> docs: Fix note tag with link

website/docs/plugin/framework/resources/state-move.mdx
The [_Resource State Move_ documentation](https://developer.hashicorp.com/terraform/plugin/framework/resources/state-move#implementation) states that a resource should implement a `StateMove` method, satisfying the `resource.ResourceWithStateMove` interface.
The interface is actually named `resource.ResourceWithMoveState`, and the method `MoveState`.
This PR corrects the documentation.
=> Correct resource State Move documentation

website/docs/plugin/framework/functions/parameters/object.mdx
Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/955
This attempts to document the existing behavior of Terraform and the framework with relation to object parameters requiring all object attributes to be explicitly configured by adding an early paragraph about the behavior. The other updates on the page are to continue the overall parameter page consistency of configuration examples being used in the implementation examples later in the pages, so here the `attr3` and `null` value handling is shown in all the examples.
In the future, there may be enhancements which could enable "optional" object attributes at which time this new documentation can be updated in relation to that potential new functionality.
=> docs: Explicitly call out object parameter attributes are required

.changes/unreleased/BUG FIXES-20240325-101108.yaml, internal/fwserver/server_planresourcechange.go, internal/fwserver/server_planresourcechange_test.go
Closes #969 
If a computed dynamic attribute is going to be marked as unknown, we need to ensure we don't use the planned state value to create the unknown value, as it could create the unknown with a concrete type. (assuming the. eventual type will be the same as prior state)
This fix, like all other dynamic changes, is intentionally pessimistic 🙂
=> internal/fwserver: Ensure computed dynamic values are marked as dynamic type during plan modification

website/docs/plugin/framework/data-sources/configure.mdx, website/docs/plugin/framework/resources/configure.mdx
Making the the code comment language match the changes from a recent tutorial PR: https://github.com/hashicorp/tutorials/pull/1945
=> Small edit for style on a code comment

.changes/unreleased/BUG FIXES-20240319-085739.yaml, .changes/unreleased/BUG FIXES-20240319-085908.yaml, .changes/unreleased/BUG FIXES-20240319-085928.yaml, types/basetypes/list_value.go, types/basetypes/list_value_test.go, types/basetypes/map_value.go, types/basetypes/map_value_test.go, types/basetypes/set_value.go, types/basetypes/set_value_test.go
A `MapValue`, `ListValue`, or `SetValue` with a nil `elementType` is an invalid state, and therefore cannot verify equality with another value. These changes to the `Equal` method now returns `false` if either the receiver or argument have a nil `elementType`.
Closes #959
=> basetypes: fix equality for values with nil elementType

website/docs/plugin/framework/resources/create.mdx
The example seems to be missing `[]` in `PlanModifiers` field.
=> Fix `PlanModifiers` usage in code-snippet

function/bool_return.go, function/dynamic_return.go, function/float64_return.go, function/int64_return.go, function/list_return.go, function/map_return.go, function/number_return.go, function/object_return.go, function/set_return.go, function/string_return.go
Followup from an out-of-band conversation. The website documentation for returns already mentions this, but it was missing from the Go package documentation.
=> function: Mention that return documentation is expected in definition documentation

.changes/unreleased/BUG FIXES-20240429-165853.yaml, .changes/unreleased/NOTES-20240429-170035.yaml, internal/fwserver/attribute_plan_modification.go, internal/fwserver/attribute_plan_modification_test.go, internal/fwserver/server_planresourcechange_test.go
Closes #993
By data definition, a null or unknown object has no underlying data where nested attributes should run plan modification. By Terraform data consistency rules, a null or unknown object should be preserved as-is (unless it is an unknown value being refined into a more known value), however this was not the case where a collection-based nested attribute had a null or unknown object, such as this example configuration:
```
resource "examplecloud_thing" "example" {
nested_map = {
examplekey = null # this was previously problematic
}
}
```
Previously, a null or unknown object would be errantly transformed by the framework plan modification logic into a known object with null/unknown attributes. This could be seen in human-readable Terraform plans, such as (`{}` below):
```
+ …
```
=> internal/fwserver: Skip automatic object state conversion and nested attributes plan modification if object is null or unknown

internal/reflect/number.go, internal/reflect/number_test.go
Relates: #1014 
This fixes a bug encountered when using `function.Float32Parameter` in a provider defined function, similar to issue #914:
```go
=== RUN   TestFloat32Function_known
float32_function_test.go:20: Step 1/1 error: Error running pre-apply plan: exit status 1
Error: Error in function call
on terraform_plugin_test.tf line 13, in output "test":
13: 					value = provider::framework::float32(1.23)
├────────────────
│ while calling provider::framework::float32(float32_param)
Call to function "provider::framework::float32" failed: Value Conversion
Error: An unexpected error was encountered trying to convert to number. This
is always an error in the provider. Please report the following to the
provider developer:
cannot store 1.23 in float32.
--- FAIL: TestFloat32Function_known (0.36s) …
```
=> reflect: Use `float64` string representation for `float32` reflection equivalency

website/docs/plugin/framework/migrating/mux.mdx
The comma in the example code is unexpected in the context and causes a parsing error
=> Remove extra unaccepted comma in the example code

website/docs/plugin/framework/handling-data/terraform-concepts.mdx
Follow-up from a recent discuss post: https://discuss.hashicorp.com/t/no-way-to-validate-an-unknown-attribute-value/68730
Our wording around unknown values was causing confusion, Terraform guarantees to call validation for non-computed attributes with a known value before applying.
=> docs: Add more clarification for unknown values during config validation

.changes/unreleased/ENHANCEMENTS-20240722-175116.yaml, .changes/unreleased/NOTES-20240801-171654.yaml, internal/reflect/helpers.go, internal/reflect/helpers_test.go, internal/reflect/struct.go, internal/reflect/struct_test.go, website/docs/plugin/framework/handling-data/types/object.mdx
Closes #242
Previous proposals: #941, #667
This PR introduces support for `types.Object` conversions with Go structs that utilize struct embedding:
- https://go.dev/ref/spec#Struct_types
- https://go.dev/doc/effective_go#embedding
This PR supports N levels of nested embedded struct types and applies the same `tfsdk` tag restrictions/validations regardless of where the tag appears in the struct.
```go
type thingResourceModel struct {
Attr1 types.String `tfsdk:"attr_1"`
Attr2 types.Bool   `tfsdk:"attr_2"`
CommonModel
}
type CommonModel struct {
Attr3 types.Int64 `tfsdk:"attr_3"`
Attr4 types.List  `tfsdk:"attr_4"`
EvenMoreCommonModel
}
type EvenMoreCommonModel struct {
Attr5 types.String `tfsdk:"attr_5"`
Attr6 types.Map    `tfsdk:"attr_6"`
}
func (r *thingResource) Schema(ctx …
```
=> all: Add support for embedded struct types in object conversions

.changes/unreleased/NOTES-20240906-095258.yaml, .github/workflows/ci-go.yml, README.md, go.mod, tools/go.mod, website/docs/plugin/framework/migrating/index.mdx
Ref: https://github.com/hashicorp/terraform-providers-devex-internal/issues/182
Bumps the minimum Go module to 1.22.0 to allow for all patch versions in 1.22. Toolchain is using the latest 1.22.7
=> all: Bump minimum Go module version to 1.22

ephemeral/close.go, ephemeral/config_validator.go, ephemeral/configure.go, ephemeral/ephemeral_resource.go, ephemeral/metadata.go, ephemeral/open.go, ephemeral/renew.go, ephemeral/schema.go, ephemeral/validate_config.go
Nice little bug found in our copyright headers for the new `ephemeral` package docs.
The repeated lines are showing up because there is a missing newline in a number of the packages, causing the header to be repeated multiple time when running `go docs ephemeral`
Prior to the change:
https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework@v1.13.0/ephemeral
After the change:
```bash
$ go doc ephemeral      
package ephemeral // import "github.com/hashicorp/terraform-plugin-framework/ephemeral"
Package ephemeral contains all interfaces, request types, and response types for
an ephemeral resource implementation.
In Terraform, an ephemeral resource is a concept which enables provider
developers to offer practitioners ephemeral values, which will not be stored
in any artifact …
```
=> docs: Fix package doc repeated copyright header

website/docs/plugin/framework/ephemeral-resources/index.mdx
Current docs link to the stable Terraform core docs, but their docs release under the beta version (`v1.10.x`)
This fixes the links:
- https://developer.hashicorp.com/terraform/language/v1.10.x/resources/ephemeral
- https://developer.hashicorp.com/terraform/language/v1.10.x/resources/ephemeral#referencing-ephemeral-resources
=> docs: Fix link to core beta documentation for ephemeral resources

.github/CODEOWNERS
I'm trying to standardize the education and web presence team's permissions across all the code repos that contain docs. Please let me know if you have any feedback!
=> Add education and web presence ability to approve PRs to website files

.changes/unreleased/BUG FIXES-20250117-110109.yaml, internal/fwschemadata/value_semantic_equality_set.go, internal/fwschemadata/value_semantic_equality_set_test.go, internal/testing/testtypes/stringwithsemanticequals.go
Closes #1061
This PR fixes the set semantic equality logic, which prior to this change, was written equivalent to list semantic equality.
Sets are unordered, so to correctly compare the semantic equality of two sets, we must compare each element in the set against all other elements to determine if there is a semantically equivalent element in the set. Once we find a semantically equal element, we remove it from the slice of candidates and continue.
----------
As an example, consider a set of case insensitive strings.
With the previous logic, the following sets would be considered semantically equal:
```bash
["value-a", "value-b", "value-c"]
["VALUE-A", "VALUE-B", "VALUE-C"]
```
However the following set would be incorrectly considered semantically not equal, due to the difference in …
=> internal/fwschemadata: Rewrite `SetValue` semantic equality logic to ignore order 

.changes/unreleased/NOTES-20250212-105343.yaml, ephemeral/doc.go, ephemeral/ephemeral_resource.go, ephemeral/schema/doc.go, provider/provider.go
=> docs: Remove experimental verbiage from ephemeral resources

.changes/unreleased/BUG FIXES-20250219-152752.yaml, internal/fwserver/server_planresourcechange.go, internal/fwserver/server_planresourcechange_test.go
Fixes: https://github.com/hashicorp/terraform-plugin-framework/issues/1096
During PlanResourceChange, computed attributes that are `null` in the configuration are marked as `unknown`. This logic only runs when there is a non-null planned state and the planned state is not equal to the prior state. If a write-only attribute is set in config, then the prior state (which is always `null`) and planned state (which contains the config value) will always differ causing `null` computed values to always be marked as `unknown` instead of using the prior value. This causes perpetual diffs after resource creation if a write-only attribute is set in config and the resource has non-null computed attribute values in state. 
The fix moves the write-only value nullification for the planned state to …
=> internal/fwserver: Move write-only nullification to earlier in PlanResourceChange

website/docs/plugin/framework/resources/write-only-arguments.mdx
Adds a callout for `PreferWriteOnlyAttribute()` validator usage about the persistent nature of the warnings for practitioners.
=> Add Callout for `PreferWriteOnlyAttribute()` validator in documentation

.changes/unreleased/NOTES-20250318-161843.yaml, .goreleaser.yml, go.mod, go.sum
This PR bumps to use the `alpha.1` release from plugin-go for resource identity.
This PR also adds a changelog for the `v1.15.0-alpha.1` pre-release, as well as sets up the goreleaser file to not show the pre-release as latest 😄 
I tried to give some minimal detail on where to look for the changes since we don't have any official documentation with this pre-release.
=> chore: Prep for `v1.15.0-alpha.1` pre-release

internal/fwschema/diagnostics.go, internal/fwtype/static_collection_validation.go, internal/fwtype/static_collection_validation_test.go, resource/identityschema/list_attribute.go, resource/identityschema/list_attribute_test.go
Most of the “invalid” identity attribute types are simply not possible to create with Framework (without abusing custom types, which we can safely ignore imo) because we have a dedicated “identityschema” package: https://github.com/hashicorp/terraform-plugin-framework/tree/main/resource/identityschema
The lone validation we need to apply at runtime is checking the element type of the “identityschema.ListAttribute” since there is no restriction on what kind of “attr.Type” is provided. The only allowed element types are:
types.Bool
types.Int64, types.Int32, types.Float64, types.Float32, types.Number
types.String
The validation was done in the ValidateImplementation function which runs during GetResourceIdentitySchemas.
Added AttributeInvalidElementTypeDiag to give the error message and …
=> Implement validation logic for "identityschema.ListAttribute"

internal/fromproto5/resource_identity.go, internal/fromproto6/resource_identity.go, internal/fwserver/server_createresource.go, internal/fwserver/server_deleteresource.go, internal/fwserver/server_importresourcestate.go, internal/fwserver/server_planresourcechange.go, internal/fwserver/server_readresource.go, internal/fwserver/server_updateresource.go, resource/resource.go
This PR just goes through and cleans up all the `TODO:ResourceIdentity` comments, of which I decided that we don't need to handle any of them ATM. We can always do some refactoring internally if we decide it's worth it later.
I also fleshed out the documentation on the `resource.ResourceWithIdentity` interface itself.
=> chore: Fix identity TODOs and add documentation for interfaces

internal/fwserver/server_importresourcestate_test.go, resource/import_state.go
**Context:** https://hashicorp.atlassian.net/browse/TFECO-9285
This PR introduces a new import helper that ensures the scenario of an "id-only refresh" can work with a single identity attribute or an import identifier. If we find there are other useful import helpers we can always introduce them later!
=> Resource Identity: Add a new import helper that can pass-through an identity attribute and an import ID.

internal/fwserver/server_applyresourcechange.go, internal/fwserver/server_applyresourcechange_test.go, internal/fwserver/server_deleteresource.go, internal/fwserver/server_deleteresource_test.go, resource/delete.go
**Context:** https://hashicorp.atlassian.net/browse/TFECO-9284
This PR introduces the `Identity` field to `DeleteRequest`. This was missed during initial implementation, despite always existing in the protocol/core. I left a comment explaining the possible confusion of using "planned" objects as a "prior" object.
=> resource: Add identity to DeleteRequest

internal/fromproto5/upgraderesourceidentity.go, internal/fromproto5/upgraderesourceidentity_test.go, internal/fromproto6/upgraderesourceidentity.go, internal/fromproto6/upgraderesourceidentity_test.go, internal/fwserver/server_upgraderesourceidentity.go, internal/fwserver/server_upgraderesourceidentity_test.go, internal/proto5server/server_upgraderesourceidentity.go, internal/proto5server/server_upgraderesourceidentity_test.go, internal/proto6server/server_upgraderesourceidentity.go, internal/proto6server/server_upgraderesourceidentity_test.go, internal/testing/testprovider/resourcewithconfigureandupgradeidentity.go, internal/testing/testprovider/resourcewithupgradeidentity.go, internal/toproto5/upgraderesourceidentity.go, internal/toproto5/upgraderesourceidentity_test.go, internal/toproto6/upgraderesourceidentity.go, internal/toproto6/upgraderesourceidentity_test.go, resource/identity_upgrader.go, resource/identityschema/schema.go, resource/resource.go, resource/upgrade_identity.go
Follow-Up PR for https://github.com/hashicorp/terraform-plugin-framework/pull/1112
This PR adds the UpgradePRC for Resource Identity to Framework.
=> Resource Identity: Add the UpgradeRPC for resource identity

internal/fromproto5/applyresourcechange.go, internal/fromproto5/applyresourcechange_test.go, internal/fromproto5/readresource.go, internal/fromproto5/readresource_test.go, internal/fromproto6/applyresourcechange.go, internal/fromproto6/applyresourcechange_test.go, internal/fromproto6/readresource.go, internal/fromproto6/readresource_test.go, internal/fwserver/server_applyresourcechange.go, internal/fwserver/server_applyresourcechange_test.go, internal/fwserver/server_importresourcestate.go, internal/fwserver/server_importresourcestate_test.go, internal/fwserver/server_planresourcechange.go, internal/fwserver/server_planresourcechange_test.go, internal/fwserver/server_readresource.go, internal/fwserver/server_readresource_test.go, internal/fwserver/server_updateresource.go, internal/privatestate/data.go, internal/proto5server/server_applyresourcechange.go, internal/proto5server/server_importresourcestate_test.go, internal/proto5server/server_readresource.go, internal/proto5server/server_readresource_test.go, internal/proto6server/server_applyresourcechange.go, internal/proto6server/server_importresourcestate_test.go, internal/proto6server/server_readresource.go, internal/proto6server/server_readresource_test.go, resource/metadata.go
This PR re-introduces the validation that previously lived in Terraform core (removed in https://github.com/hashicorp/terraform/pull/36989), which ensures that resource identities do not change after Terraform core stores them in state.
The one tricky part of this PR is `ReadResource`, which the protocol currently does not have sufficient information for us to determine if the state we are refreshing has already been stored (typical use-case) or if we are importing the resource. Rather than loosening how strict the validation is, I added a temporary key to a framework reserved `private` field, which Terraform passes between `ImportResourceState -> ReadResource`. Once we've read that field, we can skip validation of the identity, clear the `private` field, then following refreshes will …
=> ResourceIdentity: Validate that identities do not change after Terraform stores it

list/config_validator.go, list/list_resource.go, list/list_resource_test.go, list/no_op_list_resource_test.go, list/no_op_resource_test.go, list/schema.go, list/schema/schema.go, tfsdk/resource.go, tfsdk/resource_object.go
This pull request adds a top-level `list` package. `list.ListResource` is the Framework concept that defines a `list` block type, just as `ephemeral.EphemeralResource` defines an `ephemeral` block type and `resource.Resource` defines a `resource` block type.
A list resource always returns instances of a single managed resource type. For example, a `random_pet` list resource can only return instances of a `random_pet` managed resource type.
A developer can choose to implement the `list.ListResource` interface with an existing `resource.Resource`. This is intended to allow for cohesion between list resource logic and with managed resource CRUD logic.
A developer can instead choose to implement the `list.ListResource` interface separately from an existing `resource.Resource`. This is …
=> list: add types for `ListResource` support

list/list_resource.go, list/schema/schema.go, list/schema/schema_test.go, list/schema/string_attribute_test.go
- Tidy doc comments in the `list` package.
- Call out fatal error handling in `ListResultsStream`, based on discussion with Core team today.
- Removes a deprecated schema `Validate` method.
- Fixes imports in `list/schema/string_attribute_test.go`
None
=> list: tidy the doc comments and tests

internal/fwserver/server_applyresourcechange_test.go, internal/fwserver/server_planresourcechange.go, internal/fwserver/server_planresourcechange_test.go, internal/fwserver/server_readresource.go, internal/fwserver/server_readresource_test.go, internal/fwserver/server_updateresource.go
- Updated error message in `server_applyresourcechange_test.go` to correct "then" to "than" in the "Unexpected Identity Change" diagnostic message.
- Updated error message in `server_planresourcechange.go` to correct "then" to "than" in the "Unexpected Identity Change" diagnostic message.
- Updated error message in `server_planresourcechange_test.go` to correct "then" to "than" in multiple instances of the "Unexpected Identity Change" diagnostic message.
- Updated error message in `server_readresource.go` to correct "then" to "than" in the "Unexpected Identity Change" diagnostic message.
- Updated error message in `server_readresource_test.go` to correct "then" to "than" in the "Unexpected Identity Change" diagnostic message.
- Updated error message in `server_updateresource.go` to …
=> Fix grammatical errors in error messages regarding identity changes

internal/proto5server/server_getproviderschema_test.go, internal/proto6server/server_getproviderschema_test.go, internal/toproto5/getproviderschema.go, internal/toproto5/getproviderschema_test.go, internal/toproto6/getproviderschema.go, internal/toproto6/getproviderschema_test.go
Populates and return `ListResourceSchemas` in the `GetProviderSchemaResponse` method for the `GetProviderSchema` RPC for both protov5 and protov6. 
Performed some alphabetical reorderings in the expected objects as well..
None
=> list: populate and return `ListResourceSchemas` in `GetProviderSchema` for protov5 and protov6

internal/fwserver/server_listresource.go, internal/proto5server/server_listresource.go, internal/proto6server/server_listresource.go, list/list_resource.go
This pull request adds a `Limit int64` field to `list.ListResult` & propagates the `Limit` value through a `ListResource` call.
None.
=> list: add `Limit` field to `ListResult`

internal/fwserver/server_listresource.go, internal/proto5server/server_validatelistresourceconfig.go, internal/proto6server/server_validatelistresourceconfig.go
- Calls Configure in the `ListResource` RPC
- Removes a `ListResource` call in the `ValidateListResourceConfig`
None
=> list: minor fixes in `ListResource` and `ValidateListResourceConfig`

.changes/unreleased/BUG FIXES-20250612-115411.yaml, internal/fwserver/attribute_plan_modification_test.go, internal/fwserver/block_plan_modification_test.go, resource/schema/boolplanmodifier/use_state_for_unknown.go, resource/schema/boolplanmodifier/use_state_for_unknown_test.go, resource/schema/dynamicplanmodifier/use_state_for_unknown.go, resource/schema/dynamicplanmodifier/use_state_for_unknown_test.go, resource/schema/float32planmodifier/use_state_for_unknown.go, resource/schema/float32planmodifier/use_state_for_unknown_test.go, resource/schema/float64planmodifier/use_state_for_unknown.go, resource/schema/float64planmodifier/use_state_for_unknown_test.go, resource/schema/int32planmodifier/use_state_for_unknown.go, resource/schema/int32planmodifier/use_state_for_unknown_test.go, resource/schema/int64planmodifier/use_state_for_unknown.go, resource/schema/int64planmodifier/use_state_for_unknown_test.go, resource/schema/listplanmodifier/use_state_for_unknown.go, resource/schema/listplanmodifier/use_state_for_unknown_test.go, resource/schema/mapplanmodifier/use_state_for_unknown.go, resource/schema/mapplanmodifier/use_state_for_unknown_test.go, resource/schema/numberplanmodifier/use_state_for_unknown.go, resource/schema/numberplanmodifier/use_state_for_unknown_test.go, resource/schema/objectplanmodifier/use_state_for_unknown.go, resource/schema/objectplanmodifier/use_state_for_unknown_test.go, resource/schema/setplanmodifier/use_state_for_unknown.go, resource/schema/setplanmodifier/use_state_for_unknown_test.go, resource/schema/stringplanmodifier/use_state_for_unknown.go, resource/schema/stringplanmodifier/use_state_for_unknown_test.go
Related #1161
This PR backports #1161 into the `release/1.15.x` branch so we can release a `v1.15.1` module with just this change (as main currently has a couple unreleased features in it and these changes are isolated.
```bash
git cherry-pick c83bd4e010fffbbdf8147c91291776d27684fda4
```
No
=> `release/1.15.x`: Backport of #1161

.changes/1.15.1.md, CHANGELOG.md
N/A
This change brings over the release/changelog commit from the `release/v1.15.x` branch:
```bash
git cherry-pick 4781d1307f8d7b39e789717261b8f7791ac62e53
```
No
=> Sync changelog after `v1.15.1` release

internal/fwserver/server_configureprovider_test.go, internal/fwserver/server_listresource_test.go
=> list: add configure data tests for list resource

internal/proto5server/server_listresource_test.go, internal/proto6server/server_listresource_test.go, list/list_resource.go
- Sets an empty object into `ResourceIdentity` and `Resource` in the `NewListResult` method
None
=> list: set empty objects in `NewListResult`

.changes/unreleased/ENHANCEMENTS-20250916-113054.yaml, .changes/unreleased/ENHANCEMENTS-20250916-113254.yaml, .changes/unreleased/FEATURES-20250916-112534.yaml, .changes/unreleased/FEATURES-20250916-112643.yaml, .changes/unreleased/FEATURES-20250916-113807.yaml, .changes/unreleased/NOTES-20250916-112826.yaml, .changes/unreleased/NOTES-20250916-114232.yaml
n/a
This PR adds changelogs for the upcoming `v1.16.0` release, which includes action type support for Terraform 1.14+
No
=> action: Add changelogs for upcoming release

internal/proto5server/server_listresource.go, internal/proto5server/server_validatelistresourceconfig.go, internal/proto6server/server_listresource.go, internal/proto6server/server_validatelistresourceconfig.go
I noticed something was missing when I ran `TF_LOG=trace terraform query` today:
```
2025-09-16T14:23:38.070-0400 [TRACE] provider.terraform-provider-cloudlite: Checking ResourceTypes lock: @caller=/Users/baraa.basata/go/pkg/mod
/github.com/hashicorp/terraform-plugin-framework@v1.16.0-beta.1.0.20250911064719-2607d454c868/internal/logging/framework.go:29 @module=sdk.framework new_logger_warning="This log was generated by an SDK subsystem logger that wasn't created before being used. Use tflog.NewSubsystem to create this logger before it is used." timestamp=2025-09-16T14:23:36.190-0400
```
This pull request adds common Go context setup to the Framework implementations of `ListResource()` and `ValidateListResourceConfig()`. These two lines result in more correct behavior re: context …
=> Add context setup to `proto{5,6}server` `ListResource()`

.changes/unreleased/BUG FIXES-20251001-152300.yaml, internal/fwserver/server_listresource.go, internal/fwserver/server_listresource_test.go
Semi-related to validation added in:
https://github.com/hashicorp/terraform-plugin-framework/pull/1193
https://github.com/hashicorp/terraform-plugin-sdk/pull/1513
Framework allows list results with identities containing all null values, meaning providers may inadvertently forget or incorrectly set identity data. This PR changes the validation performed to also check that the values of the list result's identity are not all null.
Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.
None
=> list: update list result validation to check if identity is fully null
